//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ACC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ACC.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User  has  been  Existing.
        /// </summary>
        public static string Errors_Existing_User {
            get {
                return ResourceManager.GetString("Errors_Existing_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Expired.
        /// </summary>
        public static string User_AccountExpired {
            get {
                return ResourceManager.GetString("User_AccountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Locked.
        /// </summary>
        public static string User_AccountLocked {
            get {
                return ResourceManager.GetString("User_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been added successfully..
        /// </summary>
        public static string User_Added {
            get {
                return ResourceManager.GetString("User_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned PermissionGroups:.
        /// </summary>
        public static string User_AssignedPermissionGroups {
            get {
                return ResourceManager.GetString("User_AssignedPermissionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Permissions:.
        /// </summary>
        public static string User_AssignedPermissions {
            get {
                return ResourceManager.GetString("User_AssignedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Role:.
        /// </summary>
        public static string User_AssignedRole {
            get {
                return ResourceManager.GetString("User_AssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string User_ChangePassword_Title {
            get {
                return ResourceManager.GetString("User_ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string User_Code {
            get {
                return ResourceManager.GetString("User_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string User_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("User_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been Deleted successfully..
        /// </summary>
        public static string User_Deleted {
            get {
                return ResourceManager.GetString("User_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart.
        /// </summary>
        public static string User_Depart {
            get {
                return ResourceManager.GetString("User_Depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string User_Edit_Title {
            get {
                return ResourceManager.GetString("User_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string User_FullName {
            get {
                return ResourceManager.GetString("User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IpAddress.
        /// </summary>
        public static string User_IpAddress {
            get {
                return ResourceManager.GetString("User_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string User_IsActive {
            get {
                return ResourceManager.GetString("User_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain User.
        /// </summary>
        public static string User_IsDomainUser {
            get {
                return ResourceManager.GetString("User_IsDomainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string User_Language {
            get {
                return ResourceManager.GetString("User_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastAccessDate.
        /// </summary>
        public static string User_LastAccessDate {
            get {
                return ResourceManager.GetString("User_LastAccessDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastIpAddress.
        /// </summary>
        public static string User_LastIpAddress {
            get {
                return ResourceManager.GetString("User_LastIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastLoginDate.
        /// </summary>
        public static string User_LastLoginDate {
            get {
                return ResourceManager.GetString("User_LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastPasswordModifyDate.
        /// </summary>
        public static string User_LastPasswordModifyDate {
            get {
                return ResourceManager.GetString("User_LastPasswordModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string User_MobilePhone {
            get {
                return ResourceManager.GetString("User_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string User_New_Title {
            get {
                return ResourceManager.GetString("User_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string User_NewPassword {
            get {
                return ResourceManager.GetString("User_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPassword.
        /// </summary>
        public static string User_OldPassword {
            get {
                return ResourceManager.GetString("User_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully..
        /// </summary>
        public static string User_PasswordChanged {
            get {
                return ResourceManager.GetString("User_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expired.
        /// </summary>
        public static string User_PasswordExpired {
            get {
                return ResourceManager.GetString("User_PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Group.
        /// </summary>
        public static string User_PermissionCategoryCode {
            get {
                return ResourceManager.GetString("User_PermissionCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Category.
        /// </summary>
        public static string User_PermissionCategoryType {
            get {
                return ResourceManager.GetString("User_PermissionCategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string User_Position {
            get {
                return ResourceManager.GetString("User_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不符合复杂度要求,至少8位,大/小写/数字/符号4选2.
        /// </summary>
        public static string User_Regex {
            get {
                return ResourceManager.GetString("User_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string User_RememberMe {
            get {
                return ResourceManager.GetString("User_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string User_Role {
            get {
                return ResourceManager.GetString("User_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been assigned successfully..
        /// </summary>
        public static string User_RoleAssigned {
            get {
                return ResourceManager.GetString("User_RoleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string User_Tab_Users {
            get {
                return ResourceManager.GetString("User_Tab_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users PermissionGroups.
        /// </summary>
        public static string User_Tab_UsersPermissionGroups {
            get {
                return ResourceManager.GetString("User_Tab_UsersPermissionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Permissions.
        /// </summary>
        public static string User_Tab_UsersPermissions {
            get {
                return ResourceManager.GetString("User_Tab_UsersPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Role.
        /// </summary>
        public static string User_Tab_UsersRole {
            get {
                return ResourceManager.GetString("User_Tab_UsersRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        public static string User_TelPhone {
            get {
                return ResourceManager.GetString("User_TelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string User_Type {
            get {
                return ResourceManager.GetString("User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAssigned PermissionGroups:.
        /// </summary>
        public static string User_UnAssignedPermissionGroups {
            get {
                return ResourceManager.GetString("User_UnAssignedPermissionGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAssigned Permissions:.
        /// </summary>
        public static string User_UnAssignedPermissions {
            get {
                return ResourceManager.GetString("User_UnAssignedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAssigned Role:.
        /// </summary>
        public static string User_UnAssignedRole {
            get {
                return ResourceManager.GetString("User_UnAssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been updated successfully..
        /// </summary>
        public static string User_Updated {
            get {
                return ResourceManager.GetString("User_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User_User {
            get {
                return ResourceManager.GetString("User_User", resourceCulture);
            }
        }
    }
}
