//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.FMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CheckList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CheckList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FMS.CheckList", typeof(CheckList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList Added Successfully..
        /// </summary>
        public static string CheckList_Added {
            get {
                return ResourceManager.GetString("CheckList_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList.
        /// </summary>
        public static string CheckList_Code {
            get {
                return ResourceManager.GetString("CheckList_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList Deleted Successfully..
        /// </summary>
        public static string CheckList_Deleted {
            get {
                return ResourceManager.GetString("CheckList_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CheckList_Description {
            get {
                return ResourceManager.GetString("CheckList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string CheckList_Edit_Title {
            get {
                return ResourceManager.GetString("CheckList_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityID.
        /// </summary>
        public static string CheckList_FacilityID {
            get {
                return ResourceManager.GetString("CheckList_FacilityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CheckList_Name {
            get {
                return ResourceManager.GetString("CheckList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string CheckList_New_Title {
            get {
                return ResourceManager.GetString("CheckList_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string CheckList_Region {
            get {
                return ResourceManager.GetString("CheckList_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList Detail.
        /// </summary>
        public static string CheckListDetail_Title_View {
            get {
                return ResourceManager.GetString("CheckListDetail_Title_View", resourceCulture);
            }
        }
    }
}
