//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.FMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FacilityOrderMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FacilityOrderMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FMS.FacilityOrderMaster", typeof(FacilityOrderMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityOrderMaster Added.
        /// </summary>
        public static string FacilityOrderMaster_Added {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        public static string FacilityOrderMaster_CloseDate {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string FacilityOrderMaster_CreateDate {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserN.
        /// </summary>
        public static string FacilityOrderMaster_CreateUserName {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string FacilityOrderMaster_EndDate {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityOrder.
        /// </summary>
        public static string FacilityOrderMaster_FacilityOrderNo {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_FacilityOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string FacilityOrderMaster_LastModifyDate {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string FacilityOrderMaster_LastModifyUserNm {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_LastModifyUserNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceNo.
        /// </summary>
        public static string FacilityOrderMaster_ReferenceNo {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string FacilityOrderMaster_Region {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string FacilityOrderMaster_StartDate {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FacilityOrderMaster_Status {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityOrderDetail.
        /// </summary>
        public static string FacilityOrderMaster_Tab_FacilityOrderDetail {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_Tab_FacilityOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityOrderMaster.
        /// </summary>
        public static string FacilityOrderMaster_Title_View {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_Title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FacilityOrderMaster_Type {
            get {
                return ResourceManager.GetString("FacilityOrderMaster_Type", resourceCulture);
            }
        }
    }
}
