//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.FMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaintainPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaintainPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FMS.MaintainPlan", typeof(MaintainPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaintainPlan Added.
        /// </summary>
        public static string MaintainPlan_Added {
            get {
                return ResourceManager.GetString("MaintainPlan_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string MaintainPlan_Code {
            get {
                return ResourceManager.GetString("MaintainPlan_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaintainPlan Deleted.
        /// </summary>
        public static string MaintainPlan_Deleted {
            get {
                return ResourceManager.GetString("MaintainPlan_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MaintainPlan_Description {
            get {
                return ResourceManager.GetString("MaintainPlan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MaintainPlan_Edit_Title {
            get {
                return ResourceManager.GetString("MaintainPlan_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacilityCategory.
        /// </summary>
        public static string MaintainPlan_FacilityCategory {
            get {
                return ResourceManager.GetString("MaintainPlan_FacilityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeadTime.
        /// </summary>
        public static string MaintainPlan_LeadTime {
            get {
                return ResourceManager.GetString("MaintainPlan_LeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MaintainPlan_New_Title {
            get {
                return ResourceManager.GetString("MaintainPlan_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string MaintainPlan_Period {
            get {
                return ResourceManager.GetString("MaintainPlan_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartUpUser.
        /// </summary>
        public static string MaintainPlan_StartUpUser {
            get {
                return ResourceManager.GetString("MaintainPlan_StartUpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MaintainPlan_Type {
            get {
                return ResourceManager.GetString("MaintainPlan_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypePeriod.
        /// </summary>
        public static string MaintainPlan_TypePeriod {
            get {
                return ResourceManager.GetString("MaintainPlan_TypePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaintainPlan Updated.
        /// </summary>
        public static string MaintainPlan_Updated {
            get {
                return ResourceManager.GetString("MaintainPlan_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaintainPlanCode Exists.
        /// </summary>
        public static string MaintainPlanErrors_Existing_Code {
            get {
                return ResourceManager.GetString("MaintainPlanErrors_Existing_Code", resourceCulture);
            }
        }
    }
}
