//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your does not allow you to view this page.  Please contact your system administrator if you believe you should have access..
        /// </summary>
        public static string Errors_403 {
            get {
                return ResourceManager.GetString("Errors_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page or resource you requested was not found..
        /// </summary>
        public static string Errors_404 {
            get {
                return ResourceManager.GetString("Errors_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} can not be null。.
        /// </summary>
        public static string Errors_Common_FieldCanNotBeNull {
            get {
                return ResourceManager.GetString("Errors_Common_FieldCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Can&apos;t is less than or equal to 0..
        /// </summary>
        public static string Errors_Common_FieldEquals {
            get {
                return ResourceManager.GetString("Errors_Common_FieldEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field length cannot exceed {1} characters..
        /// </summary>
        public static string Errors_Common_FieldLengthExceed {
            get {
                return ResourceManager.GetString("Errors_Common_FieldLengthExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be between {2} and {1} characters long..
        /// </summary>
        public static string Errors_Common_FieldLengthNotInRange {
            get {
                return ResourceManager.GetString("Errors_Common_FieldLengthNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Errors_Common_FieldRequired {
            get {
                return ResourceManager.GetString("Errors_Common_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Value {1} NotExist.
        /// </summary>
        public static string Errors_Common_FieldValueNotExist {
            get {
                return ResourceManager.GetString("Errors_Common_FieldValueNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete resource, it may have been referenced..
        /// </summary>
        public static string Errors_Delete_FK_Conflict {
            get {
                return ResourceManager.GetString("Errors_Delete_FK_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code ({0}) already exists. Please try a different code..
        /// </summary>
        public static string Errors_Existing_Code {
            get {
                return ResourceManager.GetString("Errors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PermissionGroup({0}) already exists. Please try a different PermissionGroup..
        /// </summary>
        public static string Errors_Existing_PermissionGroup {
            get {
                return ResourceManager.GetString("Errors_Existing_PermissionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username ({0}) already exists. Please try a different username..
        /// </summary>
        public static string Errors_Existing_User {
            get {
                return ResourceManager.GetString("Errors_Existing_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed {0} ..
        /// </summary>
        public static string Errors_Import_Failed {
            get {
                return ResourceManager.GetString("Errors_Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}  Column{1} Value {2} Error ,Please write  Y/N..
        /// </summary>
        public static string Errors_Import_LineBooleanFieldValueError {
            get {
                return ResourceManager.GetString("Errors_Import_LineBooleanFieldValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}  Column{1} Value {2} Format Error ,Please write decimal format value..
        /// </summary>
        public static string Errors_Import_LineDecimalFieldValueErrorr_GreaterThanZero {
            get {
                return ResourceManager.GetString("Errors_Import_LineDecimalFieldValueErrorr_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}  {1} .
        /// </summary>
        public static string Errors_Import_LineError {
            get {
                return ResourceManager.GetString("Errors_Import_LineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} {1} can not be null.
        /// </summary>
        public static string Errors_Import_LineFieldCanNotBeNull {
            get {
                return ResourceManager.GetString("Errors_Import_LineFieldCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Can&apos;t is less than or equal to 0 in Line {0}..
        /// </summary>
        public static string Errors_Import_LineFieldCanNotBeZero {
            get {
                return ResourceManager.GetString("Errors_Import_LineFieldCanNotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}Can&apos;t is less than 0 in Line {0}..
        /// </summary>
        public static string Errors_Import_LineFieldCanNotLTZero {
            get {
                return ResourceManager.GetString("Errors_Import_LineFieldCanNotLTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} {1}{2} not exist ..
        /// </summary>
        public static string Errors_Import_LineFieldValueNotExist {
            get {
                return ResourceManager.GetString("Errors_Import_LineFieldValueNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}  Column{1} Value {2} Format Error ,Please write int format value..
        /// </summary>
        public static string Errors_Import_LineIntFieldValueErrorr {
            get {
                return ResourceManager.GetString("Errors_Import_LineIntFieldValueErrorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors Item {0} UomConvertion {1} - {2} NotFound.
        /// </summary>
        public static string Errors_Item_UomConvertionNotFound {
            get {
                return ResourceManager.GetString("Errors_Item_UomConvertionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password, please try again..
        /// </summary>
        public static string Errors_Login_Password_MisMatch {
            get {
                return ResourceManager.GetString("Errors_Login_Password_MisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string Errors_New_Password_And_Confirm_Password_NotEq {
            get {
                return ResourceManager.GetString("Errors_New_Password_And_Confirm_Password_NotEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input the query conditions.
        /// </summary>
        public static string Errors_NoConditions {
            get {
                return ResourceManager.GetString("Errors_NoConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record you requested was not found, it may have been deleted..
        /// </summary>
        public static string Errors_ObjectNotFound {
            get {
                return ResourceManager.GetString("Errors_ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t allow order delivery, and gathered the goods strategy can&apos;t for empty!.
        /// </summary>
        public static string Errors_PickStrategy_FieldRequired {
            get {
                return ResourceManager.GetString("Errors_PickStrategy_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was updated or deleted by another user, please reload it and try again..
        /// </summary>
        public static string Errors_StaleRecordException {
            get {
                return ResourceManager.GetString("Errors_StaleRecordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page or resource you requested was temporarily unavailable..
        /// </summary>
        public static string Errors_UnhandledException {
            get {
                return ResourceManager.GetString("Errors_UnhandledException", resourceCulture);
            }
        }
    }
}
