//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDetail.
        /// </summary>
        public static string Button_AddDetail {
            get {
                return ResourceManager.GetString("Button_AddDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust.
        /// </summary>
        public static string Button_Adjust {
            get {
                return ResourceManager.GetString("Button_Adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdjustGI.
        /// </summary>
        public static string Button_AdjustGI {
            get {
                return ResourceManager.GetString("Button_AdjustGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdjustGR.
        /// </summary>
        public static string Button_AdjustGR {
            get {
                return ResourceManager.GetString("Button_AdjustGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Adjust.
        /// </summary>
        public static string Button_AllAdjust {
            get {
                return ResourceManager.GetString("Button_AllAdjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackFlush.
        /// </summary>
        public static string Button_BackFlush {
            get {
                return ResourceManager.GetString("Button_BackFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BomDetail.
        /// </summary>
        public static string Button_BomDetail {
            get {
                return ResourceManager.GetString("Button_BomDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the shipment.
        /// </summary>
        public static string Button_Cancellations {
            get {
                return ResourceManager.GetString("Button_Cancellations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Button_ChangePassword {
            get {
                return ResourceManager.GetString("Button_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Button_Check {
            get {
                return ResourceManager.GetString("Button_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Button_Complete {
            get {
                return ResourceManager.GetString("Button_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concession.
        /// </summary>
        public static string Button_Concession {
            get {
                return ResourceManager.GetString("Button_Concession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to {0}.
        /// </summary>
        public static string Button_ConfirmOperation {
            get {
                return ResourceManager.GetString("Button_ConfirmOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatePickList.
        /// </summary>
        public static string Button_CreatePickList {
            get {
                return ResourceManager.GetString("Button_CreatePickList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRequisitionList.
        /// </summary>
        public static string Button_CreateRequisitionList {
            get {
                return ResourceManager.GetString("Button_CreateRequisitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteDetail.
        /// </summary>
        public static string Button_DeleteDetail {
            get {
                return ResourceManager.GetString("Button_DeleteDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteResult.
        /// </summary>
        public static string Button_DeleteResult {
            get {
                return ResourceManager.GetString("Button_DeleteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistributionLableCancel.
        /// </summary>
        public static string Button_DistributionLabel_Cancel {
            get {
                return ResourceManager.GetString("Button_DistributionLabel_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DistributionLabel_Export.
        /// </summary>
        public static string Button_DistributionLabel_Export {
            get {
                return ResourceManager.GetString("Button_DistributionLabel_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button_DistributionLabel_Print.
        /// </summary>
        public static string Button_DistributionLabel_Print {
            get {
                return ResourceManager.GetString("Button_DistributionLabel_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Button_Export {
            get {
                return ResourceManager.GetString("Button_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Detail.
        /// </summary>
        public static string Button_ExportDetail {
            get {
                return ResourceManager.GetString("Button_ExportDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance Calendar.
        /// </summary>
        public static string Button_FinanceCalendar {
            get {
                return ResourceManager.GetString("Button_FinanceCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        public static string Button_Freeze {
            get {
                return ResourceManager.GetString("Button_Freeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge.
        /// </summary>
        public static string Button_Judge {
            get {
                return ResourceManager.GetString("Button_Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JudgeQualify.
        /// </summary>
        public static string Button_JudgeQualify {
            get {
                return ResourceManager.GetString("Button_JudgeQualify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JudgeReject.
        /// </summary>
        public static string Button_JudgeReject {
            get {
                return ResourceManager.GetString("Button_JudgeReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBOrderBomDet.
        /// </summary>
        public static string Button_KBOrderBomDet {
            get {
                return ResourceManager.GetString("Button_KBOrderBomDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialIn.
        /// </summary>
        public static string Button_MaterialIn {
            get {
                return ResourceManager.GetString("Button_MaterialIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Button_New {
            get {
                return ResourceManager.GetString("Button_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffLine.
        /// </summary>
        public static string Button_OffLine {
            get {
                return ResourceManager.GetString("Button_OffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string Button_online {
            get {
                return ResourceManager.GetString("Button_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutToDetermine.
        /// </summary>
        public static string Button_OutToDetermine {
            get {
                return ResourceManager.GetString("Button_OutToDetermine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Button_Pause {
            get {
                return ResourceManager.GetString("Button_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        public static string Button_Pick {
            get {
                return ResourceManager.GetString("Button_Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up.
        /// </summary>
        public static string Button_PickUp {
            get {
                return ResourceManager.GetString("Button_PickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Button_Preview {
            get {
                return ResourceManager.GetString("Button_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintCard.
        /// </summary>
        public static string Button_PrintCard {
            get {
                return ResourceManager.GetString("Button_PrintCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintCardLabel.
        /// </summary>
        public static string Button_PrintCardLabel {
            get {
                return ResourceManager.GetString("Button_PrintCardLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Away.
        /// </summary>
        public static string Button_PutAway {
            get {
                return ResourceManager.GetString("Button_PutAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Button_Receive {
            get {
                return ResourceManager.GetString("Button_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string Button_Receive_Distrabution {
            get {
                return ResourceManager.GetString("Button_Receive_Distrabution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition Detail.
        /// </summary>
        public static string Button_RequisitionDetail {
            get {
                return ResourceManager.GetString("Button_RequisitionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing.
        /// </summary>
        public static string Button_Routing {
            get {
                return ResourceManager.GetString("Button_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Detail.
        /// </summary>
        public static string Button_SaveDetail {
            get {
                return ResourceManager.GetString("Button_SaveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Master.
        /// </summary>
        public static string Button_SaveMaster {
            get {
                return ResourceManager.GetString("Button_SaveMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button_SearchExport.
        /// </summary>
        public static string Button_SearchExport {
            get {
                return ResourceManager.GetString("Button_SearchExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string Button_Ship {
            get {
                return ResourceManager.GetString("Button_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Button_Start_Production {
            get {
                return ResourceManager.GetString("Button_Start_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartEmptyVanOrder.
        /// </summary>
        public static string Button_StartEmptyVanOrder {
            get {
                return ResourceManager.GetString("Button_StartEmptyVanOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Button_Transfer {
            get {
                return ResourceManager.GetString("Button_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnFreeze.
        /// </summary>
        public static string Button_UnFreeze {
            get {
                return ResourceManager.GetString("Button_UnFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string Common_CreateDate {
            get {
                return ResourceManager.GetString("Common_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string Common_CreateUserName {
            get {
                return ResourceManager.GetString("Common_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string Common_EndTime {
            get {
                return ResourceManager.GetString("Common_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modify Date.
        /// </summary>
        public static string Common_LastModifyDate {
            get {
                return ResourceManager.GetString("Common_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modify User.
        /// </summary>
        public static string Common_LastModifyUserName {
            get {
                return ResourceManager.GetString("Common_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Common_Region {
            get {
                return ResourceManager.GetString("Common_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string Common_StartTime {
            get {
                return ResourceManager.GetString("Common_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Common_To {
            get {
                return ResourceManager.GetString("Common_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Common_Type {
            get {
                return ResourceManager.GetString("Common_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Export_No {
            get {
                return ResourceManager.GetString("Export_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Export_Yes {
            get {
                return ResourceManager.GetString("Export_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DispalyType.
        /// </summary>
        public static string Grid_DispalyType {
            get {
                return ResourceManager.GetString("Grid_DispalyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Grid_DispalyType_Detail {
            get {
                return ResourceManager.GetString("Grid_DispalyType_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Grid_DispalyType_Summary {
            get {
                return ResourceManager.GetString("Grid_DispalyType_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Import Successful ..
        /// </summary>
        public static string ImportSuccess_BatchImportSuccessful {
            get {
                return ResourceManager.GetString("ImportSuccess_BatchImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Login_SiteId {
            get {
                return ResourceManager.GetString("Login_SiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Permission_Description {
            get {
                return ResourceManager.GetString("Permission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been added successfully..
        /// </summary>
        public static string PermissionGroup_Added {
            get {
                return ResourceManager.GetString("PermissionGroup_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionGroup  Name.
        /// </summary>
        public static string PermissionGroup_Code {
            get {
                return ResourceManager.GetString("PermissionGroup_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been Deleted successfully..
        /// </summary>
        public static string PermissionGroup_Deleted {
            get {
                return ResourceManager.GetString("PermissionGroup_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissionGroup  Description.
        /// </summary>
        public static string PermissionGroup_Desc {
            get {
                return ResourceManager.GetString("PermissionGroup_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PermissionGroup.
        /// </summary>
        public static string PermissionGroup_Edit_Title {
            get {
                return ResourceManager.GetString("PermissionGroup_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role has been Updated successfully..
        /// </summary>
        public static string PermissionGroup_Updated {
            get {
                return ResourceManager.GetString("PermissionGroup_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapOrderType.
        /// </summary>
        public static string SapOrderType {
            get {
                return ResourceManager.GetString("SapOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
    }
}
