//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mileage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mileage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TMS.Mileage", typeof(Mileage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Mileage_Code {
            get {
                return ResourceManager.GetString("Mileage_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string Mileage_CreateDate {
            get {
                return ResourceManager.GetString("Mileage_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string Mileage_CreateUserName {
            get {
                return ResourceManager.GetString("Mileage_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Mileage_Description {
            get {
                return ResourceManager.GetString("Mileage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Title.
        /// </summary>
        public static string Mileage_Edit_Title {
            get {
                return ResourceManager.GetString("Mileage_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string Mileage_LastModifyDate {
            get {
                return ResourceManager.GetString("Mileage_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string Mileage_LastModifyUserName {
            get {
                return ResourceManager.GetString("Mileage_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Added.
        /// </summary>
        public static string Mileage_Mileage_Added {
            get {
                return ResourceManager.GetString("Mileage_Mileage_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Deleted.
        /// </summary>
        public static string Mileage_Mileage_Deleted {
            get {
                return ResourceManager.GetString("Mileage_Mileage_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Updated.
        /// </summary>
        public static string Mileage_Mileage_Updated {
            get {
                return ResourceManager.GetString("Mileage_Mileage_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Title.
        /// </summary>
        public static string Mileage_New_Title {
            get {
                return ResourceManager.GetString("Mileage_New_Title", resourceCulture);
            }
        }
    }
}
