//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransportFlow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportFlow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TMS.TransportFlow", typeof(TransportFlow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商.
        /// </summary>
        public static string TransportFlow_FlowCarrier {
            get {
                return ResourceManager.GetString("TransportFlow_FlowCarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输站点.
        /// </summary>
        public static string TransportFlow_FlowStation {
            get {
                return ResourceManager.GetString("TransportFlow_FlowStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string TransportFlow_Sequence {
            get {
                return ResourceManager.GetString("TransportFlow_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输路线.
        /// </summary>
        public static string TransportFlow_Title {
            get {
                return ResourceManager.GetString("TransportFlow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账单地址.
        /// </summary>
        public static string TransportFlowCarrier_BillAddress {
            get {
                return ResourceManager.GetString("TransportFlowCarrier_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商代码.
        /// </summary>
        public static string TransportFlowCarrier_Carrier {
            get {
                return ResourceManager.GetString("TransportFlowCarrier_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商名称.
        /// </summary>
        public static string TransportFlowCarrier_CarrierName {
            get {
                return ResourceManager.GetString("TransportFlowCarrier_CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格单.
        /// </summary>
        public static string TransportFlowCarrier_PriceList {
            get {
                return ResourceManager.GetString("TransportFlowCarrier_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输方式.
        /// </summary>
        public static string TransportFlowCarrier_TransportMode {
            get {
                return ResourceManager.GetString("TransportFlowCarrier_TransportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路线代码.
        /// </summary>
        public static string TransportFlowMaster_Code {
            get {
                return ResourceManager.GetString("TransportFlowMaster_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路线描述.
        /// </summary>
        public static string TransportFlowMaster_Description {
            get {
                return ResourceManager.GetString("TransportFlowMaster_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可用.
        /// </summary>
        public static string TransportFlowMaster_IsActive {
            get {
                return ResourceManager.GetString("TransportFlowMaster_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动释放.
        /// </summary>
        public static string TransportFlowMaster_IsAutoRelease {
            get {
                return ResourceManager.GetString("TransportFlowMaster_IsAutoRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动开始.
        /// </summary>
        public static string TransportFlowMaster_IsAutoStart {
            get {
                return ResourceManager.GetString("TransportFlowMaster_IsAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放行配载率.
        /// </summary>
        public static string TransportFlowMaster_MinLoadRate {
            get {
                return ResourceManager.GetString("TransportFlowMaster_MinLoadRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 多点提货.
        /// </summary>
        public static string TransportFlowMaster_MultiSitePick {
            get {
                return ResourceManager.GetString("TransportFlowMaster_MultiSitePick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货运地址代码.
        /// </summary>
        public static string TransportFlowRoute_ShipAddress {
            get {
                return ResourceManager.GetString("TransportFlowRoute_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 货运地址描述.
        /// </summary>
        public static string TransportFlowRoute_ShipAddressDescription {
            get {
                return ResourceManager.GetString("TransportFlowRoute_ShipAddressDescription", resourceCulture);
            }
        }
    }
}
