//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.TMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransportPriceList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransportPriceList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TMS.TransportPriceList", typeof(TransportPriceList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商代码.
        /// </summary>
        public static string TransportPriceList_Carrier {
            get {
                return ResourceManager.GetString("TransportPriceList_Carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 承运商名称.
        /// </summary>
        public static string TransportPriceList_CarrierName {
            get {
                return ResourceManager.GetString("TransportPriceList_CarrierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代码.
        /// </summary>
        public static string TransportPriceList_Code {
            get {
                return ResourceManager.GetString("TransportPriceList_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 描述.
        /// </summary>
        public static string TransportPriceList_Description {
            get {
                return ResourceManager.GetString("TransportPriceList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可用.
        /// </summary>
        public static string TransportPriceList_IsActive {
            get {
                return ResourceManager.GetString("TransportPriceList_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运输方式.
        /// </summary>
        public static string TransportPriceList_TransportMode {
            get {
                return ResourceManager.GetString("TransportPriceList_TransportMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 币种.
        /// </summary>
        public static string TransportPriceListDetail_Currency {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提送费.
        /// </summary>
        public static string TransportPriceListDetail_DeliveryFee {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_DeliveryFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string TransportPriceListDetail_EndDate {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束数量.
        /// </summary>
        public static string TransportPriceListDetail_EndQty {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_EndQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂估价.
        /// </summary>
        public static string TransportPriceListDetail_IsProvEst {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_IsProvEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卸货费.
        /// </summary>
        public static string TransportPriceListDetail_LoadingFee {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_LoadingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高运费.
        /// </summary>
        public static string TransportPriceListDetail_MaxPrice {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_MaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最低运费.
        /// </summary>
        public static string TransportPriceListDetail_MinPrice {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 价格单.
        /// </summary>
        public static string TransportPriceListDetail_PriceList {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计价方式.
        /// </summary>
        public static string TransportPriceListDetail_PricingMethod {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_PricingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务费.
        /// </summary>
        public static string TransportPriceListDetail_ServiceFee {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_ServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 始发地.
        /// </summary>
        public static string TransportPriceListDetail_ShipFrom {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 始发地名称.
        /// </summary>
        public static string TransportPriceListDetail_ShipFromDescription {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_ShipFromDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地.
        /// </summary>
        public static string TransportPriceListDetail_ShipTo {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地名称.
        /// </summary>
        public static string TransportPriceListDetail_ShipToDescription {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_ShipToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始日期.
        /// </summary>
        public static string TransportPriceListDetail_StartDate {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始数量.
        /// </summary>
        public static string TransportPriceListDetail_StartQty {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_StartQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 吨位.
        /// </summary>
        public static string TransportPriceListDetail_Tonnage {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_Tonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单价.
        /// </summary>
        public static string TransportPriceListDetail_UnitPrice {
            get {
                return ResourceManager.GetString("TransportPriceListDetail_UnitPrice", resourceCulture);
            }
        }
    }
}
