//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ISS {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueLevel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueLevel() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ISS.IssueLevel", typeof(IssueLevel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit IssueLevel 的本地化字符串。
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueLevel  has  been  Existing 的本地化字符串。
        /// </summary>
        public static string Errors_Existing_IssueLevel {
            get {
                return ResourceManager.GetString("Errors_Existing_IssueLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsActive 的本地化字符串。
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Default 的本地化字符串。
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process InProcess 的本地化字符串。
        /// </summary>
        public static string IsInProcess {
            get {
                return ResourceManager.GetString("IsInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Submit 的本地化字符串。
        /// </summary>
        public static string IsSubmit {
            get {
                return ResourceManager.GetString("IsSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueLevel has been added successfully. 的本地化字符串。
        /// </summary>
        public static string IssueLevel_Added {
            get {
                return ResourceManager.GetString("IssueLevel_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueLevel has been Deleted successfully. 的本地化字符串。
        /// </summary>
        public static string IssueLevel_Deleted {
            get {
                return ResourceManager.GetString("IssueLevel_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueLevel has been updated successfully. 的本地化字符串。
        /// </summary>
        public static string IssueLevel_Updated {
            get {
                return ResourceManager.GetString("IssueLevel_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New IssueLevel 的本地化字符串。
        /// </summary>
        public static string New_Title {
            get {
                return ResourceManager.GetString("New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
    }
}
