//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ISS {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IssueDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssueDetail() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ISS.IssueDetail", typeof(IssueDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Date 的本地化字符串。
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateFrom 的本地化字符串。
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTo 的本地化字符串。
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Count 的本地化字符串。
        /// </summary>
        public static string EmailCount {
            get {
                return ResourceManager.GetString("EmailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Status 的本地化字符串。
        /// </summary>
        public static string EmailStatus {
            get {
                return ResourceManager.GetString("EmailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Active 的本地化字符串。
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Default 的本地化字符串。
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string IsEmail {
            get {
                return ResourceManager.GetString("IsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is InProcess 的本地化字符串。
        /// </summary>
        public static string IsInProcess {
            get {
                return ResourceManager.GetString("IsInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS 的本地化字符串。
        /// </summary>
        public static string IsSMS {
            get {
                return ResourceManager.GetString("IsSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Submit 的本地化字符串。
        /// </summary>
        public static string IsSubmit {
            get {
                return ResourceManager.GetString("IsSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue Code 的本地化字符串。
        /// </summary>
        public static string IssueCode {
            get {
                return ResourceManager.GetString("IssueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue Detail 的本地化字符串。
        /// </summary>
        public static string IssueDetail_Title {
            get {
                return ResourceManager.GetString("IssueDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssueLevel 的本地化字符串。
        /// </summary>
        public static string IssueLevel {
            get {
                return ResourceManager.GetString("IssueLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile Phone 的本地化字符串。
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority 的本地化字符串。
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile Phone Count 的本地化字符串。
        /// </summary>
        public static string SMSCount {
            get {
                return ResourceManager.GetString("SMSCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMS Status 的本地化字符串。
        /// </summary>
        public static string SMSStatus {
            get {
                return ResourceManager.GetString("SMSStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Code 的本地化字符串。
        /// </summary>
        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
