//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.Sconit.PrintMonitor.PUB_PrintOrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.Sconit.WebService.SI.PUB_PrintOrderService/", ConfigurationName="PUB_PrintOrderService.PUB_PrintOrderServiceSoap")]
    public interface PUB_PrintOrderServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.WebService.SI.PUB_PrintOrderService/GetPubPrintOrderList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityBase))]
        com.Sconit.PrintMonitor.PUB_PrintOrderService.PubPrintOrder[] GetPubPrintOrderList(string clientCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.WebService.SI.PUB_PrintOrderService/")]
    public partial class PubPrintOrder : EntityBase {
        
        private int idField;
        
        private string excelTemplateField;
        
        private string codeField;
        
        private string printerField;
        
        private string clientField;
        
        private bool isPrintedField;
        
        private string printUrlField;
        
        private int createUserIdField;
        
        private string createUserNameField;
        
        private System.DateTime createDateField;
        
        private int lastModifyUserIdField;
        
        private string lastModifyUserNameField;
        
        private System.DateTime lastModifyDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExcelTemplate {
            get {
                return this.excelTemplateField;
            }
            set {
                this.excelTemplateField = value;
                this.RaisePropertyChanged("ExcelTemplate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Printer {
            get {
                return this.printerField;
            }
            set {
                this.printerField = value;
                this.RaisePropertyChanged("Printer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsPrinted {
            get {
                return this.isPrintedField;
            }
            set {
                this.isPrintedField = value;
                this.RaisePropertyChanged("IsPrinted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PrintUrl {
            get {
                return this.printUrlField;
            }
            set {
                this.printUrlField = value;
                this.RaisePropertyChanged("PrintUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CreateUserId {
            get {
                return this.createUserIdField;
            }
            set {
                this.createUserIdField = value;
                this.RaisePropertyChanged("CreateUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
                this.RaisePropertyChanged("CreateUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int LastModifyUserId {
            get {
                return this.lastModifyUserIdField;
            }
            set {
                this.lastModifyUserIdField = value;
                this.RaisePropertyChanged("LastModifyUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LastModifyUserName {
            get {
                return this.lastModifyUserNameField;
            }
            set {
                this.lastModifyUserNameField = value;
                this.RaisePropertyChanged("LastModifyUserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime LastModifyDate {
            get {
                return this.lastModifyDateField;
            }
            set {
                this.lastModifyDateField = value;
                this.RaisePropertyChanged("LastModifyDate");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PubPrintOrder))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.WebService.SI.PUB_PrintOrderService/")]
    public abstract partial class EntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PUB_PrintOrderServiceSoapChannel : com.Sconit.PrintMonitor.PUB_PrintOrderService.PUB_PrintOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PUB_PrintOrderServiceSoapClient : System.ServiceModel.ClientBase<com.Sconit.PrintMonitor.PUB_PrintOrderService.PUB_PrintOrderServiceSoap>, com.Sconit.PrintMonitor.PUB_PrintOrderService.PUB_PrintOrderServiceSoap {
        
        public PUB_PrintOrderServiceSoapClient() {
        }
        
        public PUB_PrintOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PUB_PrintOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB_PrintOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB_PrintOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public com.Sconit.PrintMonitor.PUB_PrintOrderService.PubPrintOrder[] GetPubPrintOrderList(string clientCode) {
            return base.Channel.GetPubPrintOrderList(clientCode);
        }
    }
}
