//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.PRD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShiftMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShiftMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PRD.ShiftMaster", typeof(ShiftMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlowShiftDetail_TabDetail.
        /// </summary>
        public static string FlowShiftDetail_TabDetail {
            get {
                return ResourceManager.GetString("FlowShiftDetail_TabDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftMaster has been added successfully..
        /// </summary>
        public static string ShiftMaster_Added {
            get {
                return ResourceManager.GetString("ShiftMaster_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ShiftMaster_Code {
            get {
                return ResourceManager.GetString("ShiftMaster_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftMaster has been deleted successfully..
        /// </summary>
        public static string ShiftMaster_Deleted {
            get {
                return ResourceManager.GetString("ShiftMaster_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string ShiftMaster_Detail {
            get {
                return ResourceManager.GetString("ShiftMaster_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ShiftMaster.
        /// </summary>
        public static string ShiftMaster_Edit_Title {
            get {
                return ResourceManager.GetString("ShiftMaster_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}:{1}Can not be Empty..
        /// </summary>
        public static string ShiftMaster_LineFieldCanNotBeNull {
            get {
                return ResourceManager.GetString("ShiftMaster_LineFieldCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ShiftMaster_Name {
            get {
                return ResourceManager.GetString("ShiftMaster_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ShiftMaster.
        /// </summary>
        public static string ShiftMaster_New_Title {
            get {
                return ResourceManager.GetString("ShiftMaster_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} line: route the vendor delivery period of reference to the frequency of breakdown, please re-confirm the save number..
        /// </summary>
        public static string ShiftMaster_NotDeletedShiftMaster {
            get {
                return ResourceManager.GetString("ShiftMaster_NotDeletedShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0}: route vendor delivery period refers to the frequency of detail can not be modified..
        /// </summary>
        public static string ShiftMaster_NotUpdatedShiftMaster {
            get {
                return ResourceManager.GetString("ShiftMaster_NotUpdatedShiftMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save ShiftMaster.
        /// </summary>
        public static string ShiftMaster_Save {
            get {
                return ResourceManager.GetString("ShiftMaster_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string ShiftMaster_Shift {
            get {
                return ResourceManager.GetString("ShiftMaster_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftMaster has been updated successfully..
        /// </summary>
        public static string ShiftMaster_Updated {
            get {
                return ResourceManager.GetString("ShiftMaster_Updated", resourceCulture);
            }
        }
    }
}
