//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Hu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.Hu", typeof(Hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bin 的本地化字符串。
        /// </summary>
        public static string Bin {
            get {
                return ResourceManager.GetString("Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AgedQty 的本地化字符串。
        /// </summary>
        public static string Hu_AgedQty {
            get {
                return ResourceManager.GetString("Hu_AgedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AgingEndTime 的本地化字符串。
        /// </summary>
        public static string Hu_AgingEndTime {
            get {
                return ResourceManager.GetString("Hu_AgingEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AgingQty 的本地化字符串。
        /// </summary>
        public static string Hu_AgingQty {
            get {
                return ResourceManager.GetString("Hu_AgingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AgingStartTime 的本地化字符串。
        /// </summary>
        public static string Hu_AgingStartTime {
            get {
                return ResourceManager.GetString("Hu_AgingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConcessionCount 的本地化字符串。
        /// </summary>
        public static string Hu_ConcessionCount {
            get {
                return ResourceManager.GetString("Hu_ConcessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContainerDesc 的本地化字符串。
        /// </summary>
        public static string Hu_ContainerDesc {
            get {
                return ResourceManager.GetString("Hu_ContainerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateDate 的本地化字符串。
        /// </summary>
        public static string Hu_CreateDate {
            get {
                return ResourceManager.GetString("Hu_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateUserName 的本地化字符串。
        /// </summary>
        public static string Hu_CreateUserName {
            get {
                return ResourceManager.GetString("Hu_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DevanningQty 的本地化字符串。
        /// </summary>
        public static string Hu_DevanningQty {
            get {
                return ResourceManager.GetString("Hu_DevanningQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DevanningQty1 的本地化字符串。
        /// </summary>
        public static string Hu_DevanningQty1 {
            get {
                return ResourceManager.GetString("Hu_DevanningQty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DevanningQty2 的本地化字符串。
        /// </summary>
        public static string Hu_DevanningQty2 {
            get {
                return ResourceManager.GetString("Hu_DevanningQty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DevanningQty3 的本地化字符串。
        /// </summary>
        public static string Hu_DevanningQty3 {
            get {
                return ResourceManager.GetString("Hu_DevanningQty3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DevanningQty4 的本地化字符串。
        /// </summary>
        public static string Hu_DevanningQty4 {
            get {
                return ResourceManager.GetString("Hu_DevanningQty4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Devanning Successfully 的本地化字符串。
        /// </summary>
        public static string Hu_DevanningSuccessfully {
            get {
                return ResourceManager.GetString("Hu_DevanningSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        public static string Hu_Direction {
            get {
                return ResourceManager.GetString("Hu_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate 的本地化字符串。
        /// </summary>
        public static string Hu_EndDate {
            get {
                return ResourceManager.GetString("Hu_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpireDate 的本地化字符串。
        /// </summary>
        public static string Hu_ExpireDate {
            get {
                return ResourceManager.GetString("Hu_ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExternalOrderNo 的本地化字符串。
        /// </summary>
        public static string Hu_ExternalOrderNo {
            get {
                return ResourceManager.GetString("Hu_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FirstInventoryDate 的本地化字符串。
        /// </summary>
        public static string Hu_FirstInventoryDate {
            get {
                return ResourceManager.GetString("Hu_FirstInventoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string Hu_Flow {
            get {
                return ResourceManager.GetString("Hu_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowDetail 的本地化字符串。
        /// </summary>
        public static string Hu_FlowDetail {
            get {
                return ResourceManager.GetString("Hu_FlowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Not Check 的本地化字符串。
        /// </summary>
        public static string HU_Hu_Not_Check {
            get {
                return ResourceManager.GetString("HU_Hu_Not_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuAction 的本地化字符串。
        /// </summary>
        public static string Hu_HuAction {
            get {
                return ResourceManager.GetString("Hu_HuAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Created 的本地化字符串。
        /// </summary>
        public static string Hu_HuCreatedByFlow {
            get {
                return ResourceManager.GetString("Hu_HuCreatedByFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Created 的本地化字符串。
        /// </summary>
        public static string Hu_HuCreatedByOrder {
            get {
                return ResourceManager.GetString("Hu_HuCreatedByOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuId 的本地化字符串。
        /// </summary>
        public static string Hu_HuId {
            get {
                return ResourceManager.GetString("Hu_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuOption 的本地化字符串。
        /// </summary>
        public static string Hu_HuOption {
            get {
                return ResourceManager.GetString("Hu_HuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuOptionTypeDescription 的本地化字符串。
        /// </summary>
        public static string Hu_HuOptionTypeDescription {
            get {
                return ResourceManager.GetString("Hu_HuOptionTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuPrintedByIpMaster 的本地化字符串。
        /// </summary>
        public static string Hu_HuPrintedByIpMaster {
            get {
                return ResourceManager.GetString("Hu_HuPrintedByIpMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuQualityTypeDescription 的本地化字符串。
        /// </summary>
        public static string Hu_HuQualityTypeDescription {
            get {
                return ResourceManager.GetString("Hu_HuQualityTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuStatusDescription 的本地化字符串。
        /// </summary>
        public static string Hu_HuStatusDescription {
            get {
                return ResourceManager.GetString("Hu_HuStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OccupyTypeDescription 的本地化字符串。
        /// </summary>
        public static string Hu_HuStatusOccupyTypeDescription {
            get {
                return ResourceManager.GetString("Hu_HuStatusOccupyTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条码模板 的本地化字符串。
        /// </summary>
        public static string Hu_HuTemplate {
            get {
                return ResourceManager.GetString("Hu_HuTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpDetail 的本地化字符串。
        /// </summary>
        public static string Hu_IpDetail {
            get {
                return ResourceManager.GetString("Hu_IpDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpNo 的本地化字符串。
        /// </summary>
        public static string Hu_IpNo {
            get {
                return ResourceManager.GetString("Hu_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsChangeUnitCount 的本地化字符串。
        /// </summary>
        public static string Hu_IsChangeUnitCount {
            get {
                return ResourceManager.GetString("Hu_IsChangeUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsOdd 的本地化字符串。
        /// </summary>
        public static string Hu_IsOdd {
            get {
                return ResourceManager.GetString("Hu_IsOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsPrintPallet 的本地化字符串。
        /// </summary>
        public static string Hu_IsPrintPallet {
            get {
                return ResourceManager.GetString("Hu_IsPrintPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string Hu_Item {
            get {
                return ResourceManager.GetString("Hu_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string Hu_ItemDescription {
            get {
                return ResourceManager.GetString("Hu_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemVersion 的本地化字符串。
        /// </summary>
        public static string Hu_ItemVersion {
            get {
                return ResourceManager.GetString("Hu_ItemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyDate 的本地化字符串。
        /// </summary>
        public static string Hu_LastModifyDate {
            get {
                return ResourceManager.GetString("Hu_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyUserName 的本地化字符串。
        /// </summary>
        public static string Hu_LastModifyUserName {
            get {
                return ResourceManager.GetString("Hu_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string Hu_Length {
            get {
                return ResourceManager.GetString("Hu_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationTo 的本地化字符串。
        /// </summary>
        public static string Hu_LocationTo {
            get {
                return ResourceManager.GetString("Hu_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lotNo 的本地化字符串。
        /// </summary>
        public static string Hu_lotNo {
            get {
                return ResourceManager.GetString("Hu_lotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 lotNoTo 的本地化字符串。
        /// </summary>
        public static string Hu_lotNoTo {
            get {
                return ResourceManager.GetString("Hu_lotNoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 manufacture date 的本地化字符串。
        /// </summary>
        public static string Hu_manufacture_date {
            get {
                return ResourceManager.GetString("Hu_manufacture_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufactureParty 的本地化字符串。
        /// </summary>
        public static string Hu_ManufactureParty {
            get {
                return ResourceManager.GetString("Hu_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaterialsGroup 的本地化字符串。
        /// </summary>
        public static string Hu_MaterialsGroup {
            get {
                return ResourceManager.GetString("Hu_MaterialsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Hu_Model {
            get {
                return ResourceManager.GetString("Hu_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewExpiredDate 的本地化字符串。
        /// </summary>
        public static string Hu_NewExpiredDate {
            get {
                return ResourceManager.GetString("Hu_NewExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoNeedAgingQty 的本地化字符串。
        /// </summary>
        public static string Hu_NoNeedAgingQty {
            get {
                return ResourceManager.GetString("Hu_NoNeedAgingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NonFreezeQty 的本地化字符串。
        /// </summary>
        public static string Hu_NonFreezeQty {
            get {
                return ResourceManager.GetString("Hu_NonFreezeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OldExpiredDate 的本地化字符串。
        /// </summary>
        public static string Hu_OldExpiredDate {
            get {
                return ResourceManager.GetString("Hu_OldExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderDetail 的本地化字符串。
        /// </summary>
        public static string Hu_OrderDetail {
            get {
                return ResourceManager.GetString("Hu_OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderNo 的本地化字符串。
        /// </summary>
        public static string Hu_OrderNo {
            get {
                return ResourceManager.GetString("Hu_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PalletCode 的本地化字符串。
        /// </summary>
        public static string Hu_PalletCode {
            get {
                return ResourceManager.GetString("Hu_PalletCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PrintCount 的本地化字符串。
        /// </summary>
        public static string Hu_PrintCount {
            get {
                return ResourceManager.GetString("Hu_PrintCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 print 的本地化字符串。
        /// </summary>
        public static string Hu_Printde {
            get {
                return ResourceManager.GetString("Hu_Printde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must Check One ProductBarCode 的本地化字符串。
        /// </summary>
        public static string HU_ProductBarCode_Not_Check {
            get {
                return ResourceManager.GetString("HU_ProductBarCode_Not_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty 的本地化字符串。
        /// </summary>
        public static string Hu_Qty {
            get {
                return ResourceManager.GetString("Hu_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty0 的本地化字符串。
        /// </summary>
        public static string Hu_Qty0 {
            get {
                return ResourceManager.GetString("Hu_Qty0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty1 的本地化字符串。
        /// </summary>
        public static string Hu_Qty1 {
            get {
                return ResourceManager.GetString("Hu_Qty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty3 的本地化字符串。
        /// </summary>
        public static string Hu_Qty2 {
            get {
                return ResourceManager.GetString("Hu_Qty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty Not Match 的本地化字符串。
        /// </summary>
        public static string Hu_QtyNotMatch {
            get {
                return ResourceManager.GetString("Hu_QtyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason 的本地化字符串。
        /// </summary>
        public static string Hu_Reason {
            get {
                return ResourceManager.GetString("Hu_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiptNo 的本地化字符串。
        /// </summary>
        public static string Hu_ReceiptNo {
            get {
                return ResourceManager.GetString("Hu_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferenceItemCode 的本地化字符串。
        /// </summary>
        public static string Hu_ReferenceItemCode {
            get {
                return ResourceManager.GetString("Hu_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RefHu 的本地化字符串。
        /// </summary>
        public static string Hu_RefHu {
            get {
                return ResourceManager.GetString("Hu_RefHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string Hu_Remark {
            get {
                return ResourceManager.GetString("Hu_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindExpireDate 的本地化字符串。
        /// </summary>
        public static string Hu_RemindExpireDate {
            get {
                return ResourceManager.GetString("Hu_RemindExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindExpireDate_End 的本地化字符串。
        /// </summary>
        public static string Hu_RemindExpireDate_End {
            get {
                return ResourceManager.GetString("Hu_RemindExpireDate_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemindExpireDate_start 的本地化字符串。
        /// </summary>
        public static string Hu_RemindExpireDate_start {
            get {
                return ResourceManager.GetString("Hu_RemindExpireDate_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu Repacked 的本地化字符串。
        /// </summary>
        public static string HU_Repacked {
            get {
                return ResourceManager.GetString("HU_Repacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shift 的本地化字符串。
        /// </summary>
        public static string Hu_Shift {
            get {
                return ResourceManager.GetString("Hu_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQty 的本地化字符串。
        /// </summary>
        public static string Hu_SQty {
            get {
                return ResourceManager.GetString("Hu_SQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartDate 的本地化字符串。
        /// </summary>
        public static string Hu_StartDate {
            get {
                return ResourceManager.GetString("Hu_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuStatus 的本地化字符串。
        /// </summary>
        public static string Hu_Status {
            get {
                return ResourceManager.GetString("Hu_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SupplierLotNo 的本地化字符串。
        /// </summary>
        public static string Hu_SupplierLotNo {
            get {
                return ResourceManager.GetString("Hu_SupplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowMaster 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_FlowMaster {
            get {
                return ResourceManager.GetString("Hu_Tab_FlowMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hu 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_Hu {
            get {
                return ResourceManager.GetString("Hu_Tab_Hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPMaster 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_IPMaster {
            get {
                return ResourceManager.GetString("Hu_Tab_IPMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_Item {
            get {
                return ResourceManager.GetString("Hu_Tab_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderMaster 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_OrderMaster {
            get {
                return ResourceManager.GetString("Hu_Tab_OrderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderMaster_Production 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_OrderMaster_Production {
            get {
                return ResourceManager.GetString("Hu_Tab_OrderMaster_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parts 的本地化字符串。
        /// </summary>
        public static string Hu_Tab_Parts {
            get {
                return ResourceManager.GetString("Hu_Tab_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TotalQty 的本地化字符串。
        /// </summary>
        public static string Hu_TotalQty {
            get {
                return ResourceManager.GetString("Hu_TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnAgingQty 的本地化字符串。
        /// </summary>
        public static string Hu_UnAgingQty {
            get {
                return ResourceManager.GetString("Hu_UnAgingQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCount 的本地化字符串。
        /// </summary>
        public static string Hu_UnitCount {
            get {
                return ResourceManager.GetString("Hu_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCountDescription 的本地化字符串。
        /// </summary>
        public static string Hu_UnitCountDescription {
            get {
                return ResourceManager.GetString("Hu_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitQty 的本地化字符串。
        /// </summary>
        public static string Hu_UnitQty {
            get {
                return ResourceManager.GetString("Hu_UnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string Hu_Uom {
            get {
                return ResourceManager.GetString("Hu_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsATP 的本地化字符串。
        /// </summary>
        public static string IsATP {
            get {
                return ResourceManager.GetString("IsATP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsConsignment 的本地化字符串。
        /// </summary>
        public static string IsConsignment {
            get {
                return ResourceManager.GetString("IsConsignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsFreeze 的本地化字符串。
        /// </summary>
        public static string IsFreeze {
            get {
                return ResourceManager.GetString("IsFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OccupyReferenceNo 的本地化字符串。
        /// </summary>
        public static string OccupyReferenceNo {
            get {
                return ResourceManager.GetString("OccupyReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OccupyType 的本地化字符串。
        /// </summary>
        public static string OccupyType {
            get {
                return ResourceManager.GetString("OccupyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QualityType 的本地化字符串。
        /// </summary>
        public static string QualityType {
            get {
                return ResourceManager.GetString("QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region 的本地化字符串。
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
    }
}
