//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationTransaction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationTransaction() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.LocationTransaction", typeof(LocationTransaction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BaseUom 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_BaseUom {
            get {
                return ResourceManager.GetString("LocationTransaction_BaseUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateDate 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_CreateDate {
            get {
                return ResourceManager.GetString("LocationTransaction_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateUserId 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_CreateUserId {
            get {
                return ResourceManager.GetString("LocationTransaction_CreateUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DistributionOutQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_DistributionOutQty {
            get {
                return ResourceManager.GetString("LocationTransaction_DistributionOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EffectiveDate 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_EffectiveDate {
            get {
                return ResourceManager.GetString("LocationTransaction_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndDate 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_EndDate {
            get {
                return ResourceManager.GetString("LocationTransaction_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuId 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_HuId {
            get {
                return ResourceManager.GetString("LocationTransaction_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IoType 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_IoType {
            get {
                return ResourceManager.GetString("LocationTransaction_IoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpNo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_IpNo {
            get {
                return ResourceManager.GetString("LocationTransaction_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_Item {
            get {
                return ResourceManager.GetString("LocationTransaction_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_ItemDescription {
            get {
                return ResourceManager.GetString("LocationTransaction_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_Location {
            get {
                return ResourceManager.GetString("LocationTransaction_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationFrom 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_LocationFrom {
            get {
                return ResourceManager.GetString("LocationTransaction_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationTo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_LocationTo {
            get {
                return ResourceManager.GetString("LocationTransaction_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LotNo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_LotNo {
            get {
                return ResourceManager.GetString("LocationTransaction_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderNo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_OrderNo {
            get {
                return ResourceManager.GetString("LocationTransaction_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyFrom 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_PartyFrom {
            get {
                return ResourceManager.GetString("LocationTransaction_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyTo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_PartyTo {
            get {
                return ResourceManager.GetString("LocationTransaction_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProcurementInQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_ProcurementInQty {
            get {
                return ResourceManager.GetString("LocationTransaction_ProcurementInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionInQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_ProductionInQty {
            get {
                return ResourceManager.GetString("LocationTransaction_ProductionInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionOutQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_ProductionOutQty {
            get {
                return ResourceManager.GetString("LocationTransaction_ProductionOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_Qty {
            get {
                return ResourceManager.GetString("LocationTransaction_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality Type 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_QualityType {
            get {
                return ResourceManager.GetString("LocationTransaction_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiptNo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_ReceiptNo {
            get {
                return ResourceManager.GetString("LocationTransaction_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SequenceNo 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_SequenceNo {
            get {
                return ResourceManager.GetString("LocationTransaction_SequenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartDate 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_StartDate {
            get {
                return ResourceManager.GetString("LocationTransaction_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _TransactionType 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_TransactionType {
            get {
                return ResourceManager.GetString("LocationTransaction_TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TransferInQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_TransferInQty {
            get {
                return ResourceManager.GetString("LocationTransaction_TransferInQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TransferOutQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_TransferOutQty {
            get {
                return ResourceManager.GetString("LocationTransaction_TransferOutQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitQty 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_UnitQty {
            get {
                return ResourceManager.GetString("LocationTransaction_UnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string LocationTransaction_Uom {
            get {
                return ResourceManager.GetString("LocationTransaction_Uom", resourceCulture);
            }
        }
    }
}
