//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18047
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.INV {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StockTakeResultSummary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StockTakeResultSummary() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.INV.StockTakeResultSummary", typeof(StockTakeResultSummary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Tab_Title 的本地化字符串。
        /// </summary>
        public static string StockTakeResult_Tab_Title {
            get {
                return ResourceManager.GetString("StockTakeResult_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bin 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Bin {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BreakEvenCount 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_BreakEvenCount {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_BreakEvenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail_Title 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Detail_Title {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DifferenceQty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_DifferenceQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_DifferenceQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuId 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_HuId {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Id {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InventoryQty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_InventoryQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_InventoryQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Item {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_ItemDescription {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Location {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LotNo 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_LotNo {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MatchQty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_MatchQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_MatchQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProfitQty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_ProfitQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_ProfitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Qty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QualityType 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_QualityType {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShortageQty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_ShortageQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_ShortageQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StNo 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_StNo {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_StNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StockTakeQty 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_StockTakeQty {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_StockTakeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string StockTakeResultSummary_Uom {
            get {
                return ResourceManager.GetString("StockTakeResultSummary_Uom", resourceCulture);
            }
        }
    }
}
