//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Address {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Address() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.Address", typeof(Address).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been added successfully..
        /// </summary>
        public static string Address_Added {
            get {
                return ResourceManager.GetString("Address_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address_Address {
            get {
                return ResourceManager.GetString("Address_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Address_Code {
            get {
                return ResourceManager.GetString("Address_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactPersonName.
        /// </summary>
        public static string Address_ContactPsnNm {
            get {
                return ResourceManager.GetString("Address_ContactPsnNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been Deleted successfully..
        /// </summary>
        public static string Address_Deleted {
            get {
                return ResourceManager.GetString("Address_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Address.
        /// </summary>
        public static string Address_Edit_Title {
            get {
                return ResourceManager.GetString("Address_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Address_Email {
            get {
                return ResourceManager.GetString("Address_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Address_Fax {
            get {
                return ResourceManager.GetString("Address_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilePhone.
        /// </summary>
        public static string Address_MobilePhone {
            get {
                return ResourceManager.GetString("Address_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address.
        /// </summary>
        public static string Address_New_Title {
            get {
                return ResourceManager.GetString("Address_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Address_PostCode {
            get {
                return ResourceManager.GetString("Address_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TelPhone.
        /// </summary>
        public static string Address_TelPhone {
            get {
                return ResourceManager.GetString("Address_TelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Address_Type {
            get {
                return ResourceManager.GetString("Address_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address has been updated successfully..
        /// </summary>
        public static string Address_Updated {
            get {
                return ResourceManager.GetString("Address_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address  code has  been Existed..
        /// </summary>
        public static string AddressErrors_Existing_Code {
            get {
                return ResourceManager.GetString("AddressErrors_Existing_Code", resourceCulture);
            }
        }
    }
}
