//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinanceCalendar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinanceCalendar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.FinanceCalendar", typeof(FinanceCalendar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month must be 1-12.
        /// </summary>
        public static string Errors_FinanceCalendar_Month {
            get {
                return ResourceManager.GetString("Errors_FinanceCalendar_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the form of year is error.
        /// </summary>
        public static string Errors_FinanceCalendar_Year {
            get {
                return ResourceManager.GetString("Errors_FinanceCalendar_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceCalendar has been added successfully..
        /// </summary>
        public static string FinanceCalendar_Added {
            get {
                return ResourceManager.GetString("FinanceCalendar_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceCalendar has been deleted successfully..
        /// </summary>
        public static string FinanceCalendar_Deleted {
            get {
                return ResourceManager.GetString("FinanceCalendar_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit FinanceCalendar.
        /// </summary>
        public static string FinanceCalendar_Edit_Title {
            get {
                return ResourceManager.GetString("FinanceCalendar_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string FinanceCalendar_EndDate {
            get {
                return ResourceManager.GetString("FinanceCalendar_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceMonth.
        /// </summary>
        public static string FinanceCalendar_FinanceMonth {
            get {
                return ResourceManager.GetString("FinanceCalendar_FinanceMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceYear.
        /// </summary>
        public static string FinanceCalendar_FinanceYear {
            get {
                return ResourceManager.GetString("FinanceCalendar_FinanceYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string FinanceCalendar_Id {
            get {
                return ResourceManager.GetString("FinanceCalendar_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsClose.
        /// </summary>
        public static string FinanceCalendar_IsClose {
            get {
                return ResourceManager.GetString("FinanceCalendar_IsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New FinanceCalendar.
        /// </summary>
        public static string FinanceCalendar_New_Title {
            get {
                return ResourceManager.GetString("FinanceCalendar_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string FinanceCalendar_StartDate {
            get {
                return ResourceManager.GetString("FinanceCalendar_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinanceCalendar has been updated successfully..
        /// </summary>
        public static string FinanceCalendar_Updated {
            get {
                return ResourceManager.GetString("FinanceCalendar_Updated", resourceCulture);
            }
        }
    }
}
