//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemRef {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemRef() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.ItemRef", typeof(ItemRef).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item and Party can not be diffent..
        /// </summary>
        public static string ItemPartyErrors_Existing_Code {
            get {
                return ResourceManager.GetString("ItemPartyErrors_Existing_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRef has been added successfully..
        /// </summary>
        public static string ItemRef_Added {
            get {
                return ResourceManager.GetString("ItemRef_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRef has been deleted successfully..
        /// </summary>
        public static string ItemRef_Deleted {
            get {
                return ResourceManager.GetString("ItemRef_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ItemRef.
        /// </summary>
        public static string ItemRef_Edit_Title {
            get {
                return ResourceManager.GetString("ItemRef_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ItemRef_Id {
            get {
                return ResourceManager.GetString("ItemRef_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string ItemRef_IsActive {
            get {
                return ResourceManager.GetString("ItemRef_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemRef_Item {
            get {
                return ResourceManager.GetString("ItemRef_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ItemRef.
        /// </summary>
        public static string ItemRef_New_Title {
            get {
                return ResourceManager.GetString("ItemRef_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string ItemRef_Party {
            get {
                return ResourceManager.GetString("ItemRef_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefCode.
        /// </summary>
        public static string ItemRef_RefCode {
            get {
                return ResourceManager.GetString("ItemRef_RefCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRef.
        /// </summary>
        public static string ItemRef_Tab_Title {
            get {
                return ResourceManager.GetString("ItemRef_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemRef has been updated successfully..
        /// </summary>
        public static string ItemRef_Updated {
            get {
                return ResourceManager.GetString("ItemRef_Updated", resourceCulture);
            }
        }
    }
}
