//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItemPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MD.ItemPackage", typeof(ItemPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemPackage has been added successully..
        /// </summary>
        public static string ItemPackage_Added {
            get {
                return ResourceManager.GetString("ItemPackage_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemPackage has been deleted successully..
        /// </summary>
        public static string ItemPackage_Deleted {
            get {
                return ResourceManager.GetString("ItemPackage_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ItemPackage_Description {
            get {
                return ResourceManager.GetString("ItemPackage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ItemPackage.
        /// </summary>
        public static string ItemPackage_Edit_Title {
            get {
                return ResourceManager.GetString("ItemPackage_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ItemPackage_Id {
            get {
                return ResourceManager.GetString("ItemPackage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDefault.
        /// </summary>
        public static string ItemPackage_IsDefault {
            get {
                return ResourceManager.GetString("ItemPackage_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemPackage_Item {
            get {
                return ResourceManager.GetString("ItemPackage_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ItemPackage.
        /// </summary>
        public static string ItemPackage_New_Title {
            get {
                return ResourceManager.GetString("ItemPackage_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemPackage.
        /// </summary>
        public static string ItemPackage_Tab_Title {
            get {
                return ResourceManager.GetString("ItemPackage_Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UC.
        /// </summary>
        public static string ItemPackage_UC {
            get {
                return ResourceManager.GetString("ItemPackage_UC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemPackage has been updated successully..
        /// </summary>
        public static string ItemPackage_Updated {
            get {
                return ResourceManager.GetString("ItemPackage_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this UnitCount is already exists.
        /// </summary>
        public static string ItemPackageErrors_Existing_ItemAndUnitCount {
            get {
                return ResourceManager.GetString("ItemPackageErrors_Existing_ItemAndUnitCount", resourceCulture);
            }
        }
    }
}
