//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Report {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HistoryInventoryView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HistoryInventoryView() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Report.HistoryInventoryView", typeof(HistoryInventoryView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ATPQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_ATPQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_ATPQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConsignmentQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_ConsignmentQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_ConsignmentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CsQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_CsQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_CsQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_Description {
            get {
                return ResourceManager.GetString("HistoryInventoryView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreezeQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_FreezeQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_FreezeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HistoryDate 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_HistoryDate {
            get {
                return ResourceManager.GetString("HistoryInventoryView_HistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InspectQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_InspectQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_InspectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemFrom 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_ItemFrom
        {
            get {
                return ResourceManager.GetString("HistoryInventoryView_ItemFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemTo 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_ItemTo {
            get {
                return ResourceManager.GetString("HistoryInventoryView_ItemTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_Location {
            get {
                return ResourceManager.GetString("HistoryInventoryView_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LotNo 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_LotNo {
            get {
                return ResourceManager.GetString("HistoryInventoryView_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufactureParty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_ManufactureParty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_Name {
            get {
                return ResourceManager.GetString("HistoryInventoryView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_Qty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QualifyQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_QualifyQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_QualifyQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RejectQty 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_RejectQty {
            get {
                return ResourceManager.GetString("HistoryInventoryView_RejectQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_Uom {
            get {
                return ResourceManager.GetString("HistoryInventoryView_Uom", resourceCulture);
            }
        }

        //--------------------------------------------

        /// <summary>
        ///   查找类似 TypeLocation 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_TypeLocation
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_TypeLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 SAPLocation 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_SAPLocation
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_SAPLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Level 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_Level
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_Level", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TheFactoryFrom 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_TheFactoryFrom
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_TheFactoryFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TheFactoryTo 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_TheFactoryTo
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_TheFactoryTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 PlantFrom 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_PlantFrom
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_PlantFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 PlantTo 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_PlantTo
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_PlantTo", resourceCulture);
            }
        }
        //-------------------------------------------------------------------
        /// <summary>
        ///   查找类似 RegionFrom 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_RegionFrom
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_RegionFrom", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 RegionTo 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_RegionTo
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_RegionTo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 LocationFrom 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_LocationFrom
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_LocationFrom", resourceCulture);
            }
        }


        /// <summary>
        ///   查找类似 LocationTo 的本地化字符串。
        /// </summary>
        public static string HistoryInventoryView_LocationTo
        {
            get
            {
                return ResourceManager.GetString("HistoryInventoryView_LocationTo", resourceCulture);
            }
        }
    }
}
