//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Report {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationDetailIOB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationDetailIOB() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Report.LocationDetailIOB", typeof(LocationDetailIOB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Ccs 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Ccs {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Ccs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CycCnt 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_CycCnt {
            get {
                return ResourceManager.GetString("LocationDetailIOB_CycCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_End {
            get {
                return ResourceManager.GetString("LocationDetailIOB_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndCs 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_EndCs {
            get {
                return ResourceManager.GetString("LocationDetailIOB_EndCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndInp 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_EndInp {
            get {
                return ResourceManager.GetString("LocationDetailIOB_EndInp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndNml 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_EndNml {
            get {
                return ResourceManager.GetString("LocationDetailIOB_EndNml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndRej 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_EndRej {
            get {
                return ResourceManager.GetString("LocationDetailIOB_EndRej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndTotal 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_EndTotal {
            get {
                return ResourceManager.GetString("LocationDetailIOB_EndTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inp 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Inp {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Inp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssIic 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssIic {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssIic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssPo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssPo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssSo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssSo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssStr 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssStr {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssSwo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssSwo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssSwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssTr 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssTr {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssUnp 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssUnp {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssUnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssWo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_IssWo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_IssWo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Item {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_ItemDescription {
            get {
                return ResourceManager.GetString("LocationDetailIOB_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Location {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationName 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_LocationName {
            get {
                return ResourceManager.GetString("LocationDetailIOB_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Other {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qdii 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Qdii {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Qdii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctIic 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctIic {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctIic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctPo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctPo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctPo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctSo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctSo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctSo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctStr 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctStr {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctSwo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctSwo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctSwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctTr 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctTr {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctTr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctUnp 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctUnp {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctUnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RctWo 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_RctWo {
            get {
                return ResourceManager.GetString("LocationDetailIOB_RctWo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rej 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Rej {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Rej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Start {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartCs 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_StartCs {
            get {
                return ResourceManager.GetString("LocationDetailIOB_StartCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartInp 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_StartInp {
            get {
                return ResourceManager.GetString("LocationDetailIOB_StartInp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartNml 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_StartNml {
            get {
                return ResourceManager.GetString("LocationDetailIOB_StartNml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartRej 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_StartRej {
            get {
                return ResourceManager.GetString("LocationDetailIOB_StartRej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartTotal 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_StartTotal {
            get {
                return ResourceManager.GetString("LocationDetailIOB_StartTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string LocationDetailIOB_Uom {
            get {
                return ResourceManager.GetString("LocationDetailIOB_Uom", resourceCulture);
            }
        }
    }
}
