//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.WMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WMS.PickUser", typeof(PickUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUser Added.
        /// </summary>
        public static string PickUser_Added {
            get {
                return ResourceManager.GetString("PickUser_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string PickUser_CreateDate {
            get {
                return ResourceManager.GetString("PickUser_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUser.
        /// </summary>
        public static string PickUser_CreateUserName {
            get {
                return ResourceManager.GetString("PickUser_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUser Deleted.
        /// </summary>
        public static string PickUser_Deleted {
            get {
                return ResourceManager.GetString("PickUser_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PickUser_Description {
            get {
                return ResourceManager.GetString("PickUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string PickUser_Edit_Title {
            get {
                return ResourceManager.GetString("PickUser_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUser Exist.
        /// </summary>
        public static string PickUser_Errors_Existing_PickUser {
            get {
                return ResourceManager.GetString("PickUser_Errors_Existing_PickUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string PickUser_IsActive {
            get {
                return ResourceManager.GetString("PickUser_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoAssign.
        /// </summary>
        public static string PickUser_IsAutoAssign {
            get {
                return ResourceManager.GetString("PickUser_IsAutoAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string PickUser_LastModifyDate {
            get {
                return ResourceManager.GetString("PickUser_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string PickUser_LastModifyUserName {
            get {
                return ResourceManager.GetString("PickUser_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string PickUser_New_Title {
            get {
                return ResourceManager.GetString("PickUser_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickGroupCode.
        /// </summary>
        public static string PickUser_PickGroupCode {
            get {
                return ResourceManager.GetString("PickUser_PickGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUserName.
        /// </summary>
        public static string PickUser_PickUserName {
            get {
                return ResourceManager.GetString("PickUser_PickUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUser Updated.
        /// </summary>
        public static string PickUser_Updated {
            get {
                return ResourceManager.GetString("PickUser_Updated", resourceCulture);
            }
        }
    }
}
