//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.WMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WMS.ShipPlan", typeof(ShipPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string ShipPlan_Assign_Title {
            get {
                return ResourceManager.GetString("ShipPlan_Assign_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipPlan Assigned.
        /// </summary>
        public static string ShipPlan_Assigned {
            get {
                return ResourceManager.GetString("ShipPlan_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssignUser.
        /// </summary>
        public static string ShipPlan_AssignUser {
            get {
                return ResourceManager.GetString("ShipPlan_AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Uom.
        /// </summary>
        public static string ShipPlan_BaseUom {
            get {
                return ResourceManager.GetString("ShipPlan_BaseUom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLose Date.
        /// </summary>
        public static string ShipPlan_CloseDate {
            get {
                return ResourceManager.GetString("ShipPlan_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close User.
        /// </summary>
        public static string ShipPlan_CloseUserName {
            get {
                return ResourceManager.GetString("ShipPlan_CloseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string ShipPlan_CreateDate {
            get {
                return ResourceManager.GetString("ShipPlan_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string ShipPlan_CreateUserName {
            get {
                return ResourceManager.GetString("ShipPlan_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string ShipPlan_DateFrom {
            get {
                return ResourceManager.GetString("ShipPlan_DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string ShipPlan_DateTo {
            get {
                return ResourceManager.GetString("ShipPlan_DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiaplayOrderQty.
        /// </summary>
        public static string ShipPlan_DiaplayOrderQty {
            get {
                return ResourceManager.GetString("ShipPlan_DiaplayOrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiaplayPickQty.
        /// </summary>
        public static string ShipPlan_DiaplayPickQty {
            get {
                return ResourceManager.GetString("ShipPlan_DiaplayPickQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string ShipPlan_Dock {
            get {
                return ResourceManager.GetString("ShipPlan_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string ShipPlan_Flow {
            get {
                return ResourceManager.GetString("ShipPlan_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ShipPlan_Id {
            get {
                return ResourceManager.GetString("ShipPlan_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string ShipPlan_IsActive {
            get {
                return ResourceManager.GetString("ShipPlan_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOccupyInventory.
        /// </summary>
        public static string ShipPlan_IsOccupyInventory {
            get {
                return ResourceManager.GetString("ShipPlan_IsOccupyInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Ship Scan Hu.
        /// </summary>
        public static string ShipPlan_IsShipScanHu {
            get {
                return ResourceManager.GetString("ShipPlan_IsShipScanHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ShipPlan_Item {
            get {
                return ResourceManager.GetString("ShipPlan_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description.
        /// </summary>
        public static string ShipPlan_ItemDescription {
            get {
                return ResourceManager.GetString("ShipPlan_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string ShipPlan_LastModifyDate {
            get {
                return ResourceManager.GetString("ShipPlan_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string ShipPlan_LastModifyUserName {
            get {
                return ResourceManager.GetString("ShipPlan_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string ShipPlan_LocationFrom {
            get {
                return ResourceManager.GetString("ShipPlan_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName.
        /// </summary>
        public static string ShipPlan_LocationFromName {
            get {
                return ResourceManager.GetString("ShipPlan_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string ShipPlan_OrderNo {
            get {
                return ResourceManager.GetString("ShipPlan_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderQty.
        /// </summary>
        public static string ShipPlan_OrderQty {
            get {
                return ResourceManager.GetString("ShipPlan_OrderQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderSequence.
        /// </summary>
        public static string ShipPlan_OrderSequence {
            get {
                return ResourceManager.GetString("ShipPlan_OrderSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFrom.
        /// </summary>
        public static string ShipPlan_PartyFrom {
            get {
                return ResourceManager.GetString("ShipPlan_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyFromName.
        /// </summary>
        public static string ShipPlan_PartyFromName {
            get {
                return ResourceManager.GetString("ShipPlan_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyTo.
        /// </summary>
        public static string ShipPlan_PartyTo {
            get {
                return ResourceManager.GetString("ShipPlan_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyToName.
        /// </summary>
        public static string ShipPlan_PartyToName {
            get {
                return ResourceManager.GetString("ShipPlan_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked Qty.
        /// </summary>
        public static string ShipPlan_PickedQty {
            get {
                return ResourceManager.GetString("ShipPlan_PickedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Qty.
        /// </summary>
        public static string ShipPlan_PickQty {
            get {
                return ResourceManager.GetString("ShipPlan_PickQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string ShipPlan_Priority {
            get {
                return ResourceManager.GetString("ShipPlan_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Item.
        /// </summary>
        public static string ShipPlan_ReferenceItemCode {
            get {
                return ResourceManager.GetString("ShipPlan_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship.
        /// </summary>
        public static string ShipPlan_Ship_Title {
            get {
                return ResourceManager.GetString("ShipPlan_Ship_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFrom.
        /// </summary>
        public static string ShipPlan_ShipFrom {
            get {
                return ResourceManager.GetString("ShipPlan_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromAddress.
        /// </summary>
        public static string ShipPlan_ShipFromAddress {
            get {
                return ResourceManager.GetString("ShipPlan_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromCell.
        /// </summary>
        public static string ShipPlan_ShipFromCell {
            get {
                return ResourceManager.GetString("ShipPlan_ShipFromCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromContact.
        /// </summary>
        public static string ShipPlan_ShipFromContact {
            get {
                return ResourceManager.GetString("ShipPlan_ShipFromContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromFax.
        /// </summary>
        public static string ShipPlan_ShipFromFax {
            get {
                return ResourceManager.GetString("ShipPlan_ShipFromFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromTel.
        /// </summary>
        public static string ShipPlan_ShipFromTel {
            get {
                return ResourceManager.GetString("ShipPlan_ShipFromTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipGroupCode.
        /// </summary>
        public static string ShipPlan_ShipGroupCode {
            get {
                return ResourceManager.GetString("ShipPlan_ShipGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Qty.
        /// </summary>
        public static string ShipPlan_ShipQty {
            get {
                return ResourceManager.GetString("ShipPlan_ShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo.
        /// </summary>
        public static string ShipPlan_ShipTo {
            get {
                return ResourceManager.GetString("ShipPlan_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToAddress.
        /// </summary>
        public static string ShipPlan_ShipToAddress {
            get {
                return ResourceManager.GetString("ShipPlan_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToCell.
        /// </summary>
        public static string ShipPlan_ShipToCell {
            get {
                return ResourceManager.GetString("ShipPlan_ShipToCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToContact.
        /// </summary>
        public static string ShipPlan_ShipToContact {
            get {
                return ResourceManager.GetString("ShipPlan_ShipToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToFax.
        /// </summary>
        public static string ShipPlan_ShipToFax {
            get {
                return ResourceManager.GetString("ShipPlan_ShipToFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToTel.
        /// </summary>
        public static string ShipPlan_ShipToTel {
            get {
                return ResourceManager.GetString("ShipPlan_ShipToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUserName.
        /// </summary>
        public static string ShipPlan_ShipUserName {
            get {
                return ResourceManager.GetString("ShipPlan_ShipUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime.
        /// </summary>
        public static string ShipPlan_StartTime {
            get {
                return ResourceManager.GetString("ShipPlan_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipPlan.
        /// </summary>
        public static string ShipPlan_Title {
            get {
                return ResourceManager.GetString("ShipPlan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarCodeQty.
        /// </summary>
        public static string ShipPlan_ToDeliveryBarCodeQty {
            get {
                return ResourceManager.GetString("ShipPlan_ToDeliveryBarCodeQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Count.
        /// </summary>
        public static string ShipPlan_UnitCount {
            get {
                return ResourceManager.GetString("ShipPlan_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Count Description.
        /// </summary>
        public static string ShipPlan_UnitCountDescription {
            get {
                return ResourceManager.GetString("ShipPlan_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Qty.
        /// </summary>
        public static string ShipPlan_UnitQty {
            get {
                return ResourceManager.GetString("ShipPlan_UnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string ShipPlan_Uom {
            get {
                return ResourceManager.GetString("ShipPlan_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTime.
        /// </summary>
        public static string ShipPlan_WindowTime {
            get {
                return ResourceManager.GetString("ShipPlan_WindowTime", resourceCulture);
            }
        }
    }
}
