//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.WMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WMS.ShipUser", typeof(ShipUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUser Added.
        /// </summary>
        public static string ShipUser_Added {
            get {
                return ResourceManager.GetString("ShipUser_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string ShipUser_CreateDate {
            get {
                return ResourceManager.GetString("ShipUser_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUser.
        /// </summary>
        public static string ShipUser_CreateUserName {
            get {
                return ResourceManager.GetString("ShipUser_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUser Deleted.
        /// </summary>
        public static string ShipUser_Deleted {
            get {
                return ResourceManager.GetString("ShipUser_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ShipUser_Description {
            get {
                return ResourceManager.GetString("ShipUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ShipUser_Edit_Title {
            get {
                return ResourceManager.GetString("ShipUser_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUser Exist.
        /// </summary>
        public static string ShipUser_Errors_Existing_ShipUser {
            get {
                return ResourceManager.GetString("ShipUser_Errors_Existing_ShipUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string ShipUser_IsActive {
            get {
                return ResourceManager.GetString("ShipUser_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string ShipUser_LastModifyDate {
            get {
                return ResourceManager.GetString("ShipUser_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string ShipUser_LastModifyUserName {
            get {
                return ResourceManager.GetString("ShipUser_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ShipUser_New_Title {
            get {
                return ResourceManager.GetString("ShipUser_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipGroupCode.
        /// </summary>
        public static string ShipUser_ShipGroupCode {
            get {
                return ResourceManager.GetString("ShipUser_ShipGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUserName.
        /// </summary>
        public static string ShipUser_ShipUserName {
            get {
                return ResourceManager.GetString("ShipUser_ShipUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUser Updated.
        /// </summary>
        public static string ShipUser_Updated {
            get {
                return ResourceManager.GetString("ShipUser_Updated", resourceCulture);
            }
        }
    }
}
