//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderDetail() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.OrderDetail", typeof(OrderDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BillAddress 的本地化字符串。
        /// </summary>
        public static string OrderDetail_BillAddress {
            get {
                return ResourceManager.GetString("OrderDetail_BillAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BillAddressDescription 的本地化字符串。
        /// </summary>
        public static string OrderDetail_BillAddressDescription {
            get {
                return ResourceManager.GetString("OrderDetail_BillAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BillTerm 的本地化字符串。
        /// </summary>
        public static string OrderDetail_BillTerm {
            get {
                return ResourceManager.GetString("OrderDetail_BillTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bom 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Bom {
            get {
                return ResourceManager.GetString("OrderDetail_Bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BomDetail 的本地化字符串。
        /// </summary>
        public static string OrderDetail_BomDetail_Title_View {
            get {
                return ResourceManager.GetString("OrderDetail_BomDetail_Title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Container {
            get {
                return ResourceManager.GetString("OrderDetail_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContainerDescrip 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ContainerDescription {
            get {
                return ResourceManager.GetString("OrderDetail_ContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateDate 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CreateDate {
            get {
                return ResourceManager.GetString("OrderDetail_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateUserName 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CreateUserName {
            get {
                return ResourceManager.GetString("OrderDetail_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentPickListQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CurrentPickListQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentPickListQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentPickQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CurrentPickQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentPickQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentReceiveQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CurrentReceiveQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentReceiveQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentScrapQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CurrentScrapQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentScrapQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CurrentShipQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_CurrentShipQty {
            get {
                return ResourceManager.GetString("OrderDetail_CurrentShipQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Direction {
            get {
                return ResourceManager.GetString("OrderDetail_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExternalOrderNo 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ExternalOrderNo {
            get {
                return ResourceManager.GetString("OrderDetail_ExternalOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Flow {
            get {
                return ResourceManager.GetString("OrderDetail_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_HuQty {
            get {
                return ResourceManager.GetString("OrderDetail_HuQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InTransQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_InTransQty {
            get {
                return ResourceManager.GetString("OrderDetail_InTransQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InvQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_InvQty {
            get {
                return ResourceManager.GetString("OrderDetail_InvQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsIncludeTax 的本地化字符串。
        /// </summary>
        public static string OrderDetail_IsIncludeTax {
            get {
                return ResourceManager.GetString("OrderDetail_IsIncludeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsInspect 的本地化字符串。
        /// </summary>
        public static string OrderDetail_IsInspect {
            get {
                return ResourceManager.GetString("OrderDetail_IsInspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsProvisionalEstimate 的本地化字符串。
        /// </summary>
        public static string OrderDetail_IsProvisionalEstimate {
            get {
                return ResourceManager.GetString("OrderDetail_IsProvisionalEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Item {
            get {
                return ResourceManager.GetString("OrderDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ItemDescription 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ItemDescription {
            get {
                return ResourceManager.GetString("OrderDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyDate 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LastModifyDate {
            get {
                return ResourceManager.GetString("OrderDetail_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyUserName 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LastModifyUserName {
            get {
                return ResourceManager.GetString("OrderDetail_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationFrom 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LocationFrom {
            get {
                return ResourceManager.GetString("OrderDetail_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationFromName 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LocationFromName {
            get {
                return ResourceManager.GetString("OrderDetail_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LocationQty {
            get {
                return ResourceManager.GetString("OrderDetail_LocationQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationTo 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LocationTo {
            get {
                return ResourceManager.GetString("OrderDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LocationToName 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LocationToName {
            get {
                return ResourceManager.GetString("OrderDetail_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LotNo 的本地化字符串。
        /// </summary>
        public static string OrderDetail_LotNo {
            get {
                return ResourceManager.GetString("OrderDetail_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ManufactureParty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("OrderDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造商 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ManufactureParty1 {
            get {
                return ResourceManager.GetString("OrderDetail_ManufactureParty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MaxStock 的本地化字符串。
        /// </summary>
        public static string OrderDetail_MaxStock {
            get {
                return ResourceManager.GetString("OrderDetail_MaxStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinUnitCount 的本地化字符串。
        /// </summary>
        public static string OrderDetail_MinUnitCount {
            get {
                return ResourceManager.GetString("OrderDetail_MinUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Operation_Title_View {
            get {
                return ResourceManager.GetString("OrderDetail_Operation_Title_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderDetail 的本地化字符串。
        /// </summary>
        public static string OrderDetail_OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail_OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderDetails 的本地化字符串。
        /// </summary>
        public static string OrderDetail_OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetail_OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderedQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_OrderedQty {
            get {
                return ResourceManager.GetString("OrderDetail_OrderedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderedQtyReturn 的本地化字符串。
        /// </summary>
        public static string OrderDetail_OrderedQtyReturn {
            get {
                return ResourceManager.GetString("OrderDetail_OrderedQtyReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderNo 的本地化字符串。
        /// </summary>
        public static string OrderDetail_OrderNo {
            get {
                return ResourceManager.GetString("OrderDetail_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyFrom 的本地化字符串。
        /// </summary>
        public static string OrderDetail_PartyFrom {
            get {
                return ResourceManager.GetString("OrderDetail_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PickedQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_PickedQty {
            get {
                return ResourceManager.GetString("OrderDetail_PickedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PriceList 的本地化字符串。
        /// </summary>
        public static string OrderDetail_PriceList {
            get {
                return ResourceManager.GetString("OrderDetail_PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductionScan 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ProductionScan {
            get {
                return ResourceManager.GetString("OrderDetail_ProductionScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProductLineFacility 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ProductLineFacility {
            get {
                return ResourceManager.GetString("OrderDetail_ProductLineFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量状态 的本地化字符串。
        /// </summary>
        public static string OrderDetail_QualityType {
            get {
                return ResourceManager.GetString("OrderDetail_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceivedQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ReceivedQty {
            get {
                return ResourceManager.GetString("OrderDetail_ReceivedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiveLotSize 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ReceiveLotSize {
            get {
                return ResourceManager.GetString("OrderDetail_ReceiveLotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReferenceItemCode 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("OrderDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rejected Qty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_RejectedQty {
            get {
                return ResourceManager.GetString("OrderDetail_RejectedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required Qty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_RequiredQty {
            get {
                return ResourceManager.GetString("OrderDetail_RequiredQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Routing 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Routing {
            get {
                return ResourceManager.GetString("OrderDetail_Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScheduleLineNo 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ScheduleLineNo {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScheduleLineSeq 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ScheduleLineSeq {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleLineSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScheduleType 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ScheduleType {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ScheduleType_All {
            get {
                return ResourceManager.GetString("OrderDetail_ScheduleType_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScrapQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ScrapQty {
            get {
                return ResourceManager.GetString("OrderDetail_ScrapQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sequence 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Sequence {
            get {
                return ResourceManager.GetString("OrderDetail_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShippedQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_ShippedQty {
            get {
                return ResourceManager.GetString("OrderDetail_ShippedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SupplierLotNo 的本地化字符串。
        /// </summary>
        public static string OrderDetail_SupplierLotNo {
            get {
                return ResourceManager.GetString("OrderDetail_SupplierLotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tax 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Tax {
            get {
                return ResourceManager.GetString("OrderDetail_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderDetail 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Title {
            get {
                return ResourceManager.GetString("OrderDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UCDesc 的本地化字符串。
        /// </summary>
        public static string OrderDetail_UCDesc {
            get {
                return ResourceManager.GetString("OrderDetail_UCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCount 的本地化字符串。
        /// </summary>
        public static string OrderDetail_UnitCount {
            get {
                return ResourceManager.GetString("OrderDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitCountDescrip 的本地化字符串。
        /// </summary>
        public static string OrderDetail_UnitCountDescription {
            get {
                return ResourceManager.GetString("OrderDetail_UnitCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitPrice 的本地化字符串。
        /// </summary>
        public static string OrderDetail_UnitPrice {
            get {
                return ResourceManager.GetString("OrderDetail_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnitQty 的本地化字符串。
        /// </summary>
        public static string OrderDetail_UnitQty {
            get {
                return ResourceManager.GetString("OrderDetail_UnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uom 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Uom {
            get {
                return ResourceManager.GetString("OrderDetail_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string OrderDetail_Version {
            get {
                return ResourceManager.GetString("OrderDetail_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowTime 的本地化字符串。
        /// </summary>
        public static string OrderDetail_WindowTime {
            get {
                return ResourceManager.GetString("OrderDetail_WindowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WMSSeq 的本地化字符串。
        /// </summary>
        public static string OrderDetail_WMSSeq {
            get {
                return ResourceManager.GetString("OrderDetail_WMSSeq", resourceCulture);
            }
        }
    }
}
