//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderBomDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderBomDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.OrderBomDetail", typeof(OrderBomDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUFNR.
        /// </summary>
        public static string OrderBomDetail_AUFNR {
            get {
                return ResourceManager.GetString("OrderBomDetail_AUFNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackFlushMethod.
        /// </summary>
        public static string OrderBomDetail_BackFlushMethod {
            get {
                return ResourceManager.GetString("OrderBomDetail_BackFlushMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BomUnitQty.
        /// </summary>
        public static string OrderBomDetail_BomUnitQty {
            get {
                return ResourceManager.GetString("OrderBomDetail_BomUnitQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string OrderBomDetail_Deleted {
            get {
                return ResourceManager.GetString("OrderBomDetail_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedLocation.
        /// </summary>
        public static string OrderBomDetail_FeedLocation {
            get {
                return ResourceManager.GetString("OrderBomDetail_FeedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedMethod.
        /// </summary>
        public static string OrderBomDetail_FeedMethod {
            get {
                return ResourceManager.GetString("OrderBomDetail_FeedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedQty.
        /// </summary>
        public static string OrderBomDetail_FeedQty {
            get {
                return ResourceManager.GetString("OrderBomDetail_FeedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string OrderBomDetail_Flow {
            get {
                return ResourceManager.GetString("OrderBomDetail_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoFeed.
        /// </summary>
        public static string OrderBomDetail_IsAutoFeed {
            get {
                return ResourceManager.GetString("OrderBomDetail_IsAutoFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string OrderBomDetail_Item {
            get {
                return ResourceManager.GetString("OrderBomDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string OrderBomDetail_ItemDescription {
            get {
                return ResourceManager.GetString("OrderBomDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string OrderBomDetail_Location {
            get {
                return ResourceManager.GetString("OrderBomDetail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string OrderBomDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("OrderBomDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialInDetail.
        /// </summary>
        public static string OrderBomDetail_MaterialInDetail_Title {
            get {
                return ResourceManager.GetString("OrderBomDetail_MaterialInDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string OrderBomDetail_Operation {
            get {
                return ResourceManager.GetString("OrderBomDetail_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpReference.
        /// </summary>
        public static string OrderBomDetail_OpReference {
            get {
                return ResourceManager.GetString("OrderBomDetail_OpReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Goods.
        /// </summary>
        public static string OrderBomDetail_OrderDetailId {
            get {
                return ResourceManager.GetString("OrderBomDetail_OrderDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderedQty.
        /// </summary>
        public static string OrderBomDetail_OrderedQty {
            get {
                return ResourceManager.GetString("OrderBomDetail_OrderedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string OrderBomDetail_OrderedQty_Feed {
            get {
                return ResourceManager.GetString("OrderBomDetail_OrderedQty_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string OrderBomDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("OrderBomDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReserveLine.
        /// </summary>
        public static string OrderBomDetail_ReserveLine {
            get {
                return ResourceManager.GetString("OrderBomDetail_ReserveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReserveNo.
        /// </summary>
        public static string OrderBomDetail_ReserveNo {
            get {
                return ResourceManager.GetString("OrderBomDetail_ReserveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnLocation.
        /// </summary>
        public static string OrderBomDetail_ReturnLocation {
            get {
                return ResourceManager.GetString("OrderBomDetail_ReturnLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnQty.
        /// </summary>
        public static string OrderBomDetail_ReturnQty {
            get {
                return ResourceManager.GetString("OrderBomDetail_ReturnQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string OrderBomDetail_Saved {
            get {
                return ResourceManager.GetString("OrderBomDetail_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string OrderBomDetail_Uom {
            get {
                return ResourceManager.GetString("OrderBomDetail_Uom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOPDS.
        /// </summary>
        public static string OrderBomDetail_ZOPDS {
            get {
                return ResourceManager.GetString("OrderBomDetail_ZOPDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOPID.
        /// </summary>
        public static string OrderBomDetail_ZOPID {
            get {
                return ResourceManager.GetString("OrderBomDetail_ZOPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOPWZ.
        /// </summary>
        public static string OrderBomDetail_ZOPWZ {
            get {
                return ResourceManager.GetString("OrderBomDetail_ZOPWZ", resourceCulture);
            }
        }
    }
}
