//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PickListDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PickListDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.PickListDetail", typeof(PickListDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin.
        /// </summary>
        public static string PickListDetail_Bin {
            get {
                return ResourceManager.GetString("PickListDetail_Bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string PickListDetail_Direction {
            get {
                return ResourceManager.GetString("PickListDetail_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PickListDetail.
        /// </summary>
        public static string PickListDetail_Edit_Title {
            get {
                return ResourceManager.GetString("PickListDetail_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HuId.
        /// </summary>
        public static string PickListDetail_HuId {
            get {
                return ResourceManager.GetString("PickListDetail_HuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDevan.
        /// </summary>
        public static string PickListDetail_IsDevan {
            get {
                return ResourceManager.GetString("PickListDetail_IsDevan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInventory.
        /// </summary>
        public static string PickListDetail_IsInventory {
            get {
                return ResourceManager.GetString("PickListDetail_IsInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsMatchDirection.
        /// </summary>
        public static string PickListDetail_IsMatchDirection {
            get {
                return ResourceManager.GetString("PickListDetail_IsMatchDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsOdd.
        /// </summary>
        public static string PickListDetail_IsOdd {
            get {
                return ResourceManager.GetString("PickListDetail_IsOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string PickListDetail_Item {
            get {
                return ResourceManager.GetString("PickListDetail_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemCount.
        /// </summary>
        public static string PickListDetail_ItemCount {
            get {
                return ResourceManager.GetString("PickListDetail_ItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string PickListDetail_ItemDescription {
            get {
                return ResourceManager.GetString("PickListDetail_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFrom.
        /// </summary>
        public static string PickListDetail_LocationFrom {
            get {
                return ResourceManager.GetString("PickListDetail_LocationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName.
        /// </summary>
        public static string PickListDetail_LocationFromName {
            get {
                return ResourceManager.GetString("PickListDetail_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTo.
        /// </summary>
        public static string PickListDetail_LocationTo {
            get {
                return ResourceManager.GetString("PickListDetail_LocationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationToName.
        /// </summary>
        public static string PickListDetail_LocationToName {
            get {
                return ResourceManager.GetString("PickListDetail_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotNo.
        /// </summary>
        public static string PickListDetail_LotNo {
            get {
                return ResourceManager.GetString("PickListDetail_LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufactureParty.
        /// </summary>
        public static string PickListDetail_ManufactureParty {
            get {
                return ResourceManager.GetString("PickListDetail_ManufactureParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNo.
        /// </summary>
        public static string PickListDetail_OrderNo {
            get {
                return ResourceManager.GetString("PickListDetail_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickedQty.
        /// </summary>
        public static string PickListDetail_PickedQty {
            get {
                return ResourceManager.GetString("PickListDetail_PickedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickListNo.
        /// </summary>
        public static string PickListDetail_PickListNo {
            get {
                return ResourceManager.GetString("PickListDetail_PickListNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string PickListDetail_Qty {
            get {
                return ResourceManager.GetString("PickListDetail_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceItemCode.
        /// </summary>
        public static string PickListDetail_ReferenceItemCode {
            get {
                return ResourceManager.GetString("PickListDetail_ReferenceItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string PickListDetail_Sequence {
            get {
                return ResourceManager.GetString("PickListDetail_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnitCount.
        /// </summary>
        public static string PickListDetail_UnitCount {
            get {
                return ResourceManager.GetString("PickListDetail_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uom.
        /// </summary>
        public static string PickListDetail_Uom {
            get {
                return ResourceManager.GetString("PickListDetail_Uom", resourceCulture);
            }
        }
    }
}
