//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReceiptMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReceiptMaster() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.ReceiptMaster", typeof(ReceiptMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Receipt line can not be empty. 的本地化字符串。
        /// </summary>
        public static string Errors_ReceiptDetailIsEmpty {
            get {
                return ResourceManager.GetString("Errors_ReceiptDetailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CancelReason 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_CancelReason {
            get {
                return ResourceManager.GetString("ReceiptMaster_CancelReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateDate 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_CreateDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateUserName 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_CreateUserName {
            get {
                return ResourceManager.GetString("ReceiptMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_Dock {
            get {
                return ResourceManager.GetString("ReceiptMaster_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_EndDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExternalReceiptNo 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ExternalReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_ExternalReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_Flow {
            get {
                return ResourceManager.GetString("ReceiptMaster_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpNo 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IpNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_IpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsCheckPartyFromAuthority 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyFromAuthority {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyFromAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsCheckPartyFromAuthority_Customer 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyFromAuthority_Customer {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyFromAuthority_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsCheckPartyFromAuthority_Procurement 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyFromAuthority_Procurement {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyFromAuthority_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsCheckPartyToAuthority 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IsCheckPartyToAuthority {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsCheckPartyToAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsPrintReceipt 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IsPrintReceipt {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsPrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsReceiveScanHu 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_IsReceiveScanHu {
            get {
                return ResourceManager.GetString("ReceiptMaster_IsReceiveScanHu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_Item {
            get {
                return ResourceManager.GetString("ReceiptMaster_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyDate 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_LastModifyDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastModifyUserName 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_LastModifyUserName {
            get {
                return ResourceManager.GetString("ReceiptMaster_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderSubType 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_OrderSubType {
            get {
                return ResourceManager.GetString("ReceiptMaster_OrderSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubType 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_OrderSubTypeDescription {
            get {
                return ResourceManager.GetString("ReceiptMaster_OrderSubTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderType 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_OrderType {
            get {
                return ResourceManager.GetString("ReceiptMaster_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyFrom 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_PartyFrom {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyFrom_Procurement 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_PartyFrom_Procurement {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyFrom_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyFromName 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_PartyFromName {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyTo 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_PartyTo {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyTo_Procurement 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_PartyTo_Procurement {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyTo_Procurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PartyToName 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_PartyToName {
            get {
                return ResourceManager.GetString("ReceiptMaster_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiptNo 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReceiptTemplate 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ReceiptTemplate {
            get {
                return ResourceManager.GetString("ReceiptMaster_ReceiptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipFrom 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipFrom {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipFromAddress 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipFromAddress {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipFromContact 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipFromContact {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFromContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipFromTel 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipFromTel {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipFromTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipTo 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipTo {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipToAddress 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipToAddress {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipToContact 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipToContact {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShipToTel 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_ShipToTel {
            get {
                return ResourceManager.GetString("ReceiptMaster_ShipToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_StartDate {
            get {
                return ResourceManager.GetString("ReceiptMaster_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_Status {
            get {
                return ResourceManager.GetString("ReceiptMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_StatusDescription {
            get {
                return ResourceManager.GetString("ReceiptMaster_StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IpDetailType 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_Type {
            get {
                return ResourceManager.GetString("ReceiptMaster_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WMSNo 的本地化字符串。
        /// </summary>
        public static string ReceiptMaster_WMSNo {
            get {
                return ResourceManager.GetString("ReceiptMaster_WMSNo", resourceCulture);
            }
        }
    }
}
