//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ORD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SequenceMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SequenceMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ORD.SequenceMaster", typeof(SequenceMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsnTemplate.
        /// </summary>
        public static string SequenceMaster_AsnTemplate {
            get {
                return ResourceManager.GetString("SequenceMaster_AsnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutomaticControl.
        /// </summary>
        public static string SequenceMaster_AutomaticControl {
            get {
                return ResourceManager.GetString("SequenceMaster_AutomaticControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelDate.
        /// </summary>
        public static string SequenceMaster_CancelDate {
            get {
                return ResourceManager.GetString("SequenceMaster_CancelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelUserName.
        /// </summary>
        public static string SequenceMaster_CancelUserName {
            get {
                return ResourceManager.GetString("SequenceMaster_CancelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseDate.
        /// </summary>
        public static string SequenceMaster_CloseDate {
            get {
                return ResourceManager.GetString("SequenceMaster_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseUserName.
        /// </summary>
        public static string SequenceMaster_CloseUserName {
            get {
                return ResourceManager.GetString("SequenceMaster_CloseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        public static string SequenceMaster_Container {
            get {
                return ResourceManager.GetString("SequenceMaster_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainerDescription.
        /// </summary>
        public static string SequenceMaster_ContainerDescription {
            get {
                return ResourceManager.GetString("SequenceMaster_ContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string SequenceMaster_CreateDate {
            get {
                return ResourceManager.GetString("SequenceMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUserName.
        /// </summary>
        public static string SequenceMaster_CreateUserName {
            get {
                return ResourceManager.GetString("SequenceMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string SequenceMaster_Dock {
            get {
                return ResourceManager.GetString("SequenceMaster_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string SequenceMaster_EndTime {
            get {
                return ResourceManager.GetString("SequenceMaster_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string SequenceMaster_Flow {
            get {
                return ResourceManager.GetString("SequenceMaster_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAutoReceive.
        /// </summary>
        public static string SequenceMaster_IsAutoReceive {
            get {
                return ResourceManager.GetString("SequenceMaster_IsAutoReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintAsn.
        /// </summary>
        public static string SequenceMaster_IsPrintAsn {
            get {
                return ResourceManager.GetString("SequenceMaster_IsPrintAsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPrintReceipt.
        /// </summary>
        public static string SequenceMaster_IsPrintReceipt {
            get {
                return ResourceManager.GetString("SequenceMaster_IsPrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string SequenceMaster_Item {
            get {
                return ResourceManager.GetString("SequenceMaster_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyDate.
        /// </summary>
        public static string SequenceMaster_LastModifyDate {
            get {
                return ResourceManager.GetString("SequenceMaster_LastModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastModifyUserName.
        /// </summary>
        public static string SequenceMaster_LastModifyUserName {
            get {
                return ResourceManager.GetString("SequenceMaster_LastModifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationFromName.
        /// </summary>
        public static string SequenceMaster_LocationFromName {
            get {
                return ResourceManager.GetString("SequenceMaster_LocationFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationToName.
        /// </summary>
        public static string SequenceMaster_LocationToName {
            get {
                return ResourceManager.GetString("SequenceMaster_LocationToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string SequenceMaster_OrderType {
            get {
                return ResourceManager.GetString("SequenceMaster_OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackDate.
        /// </summary>
        public static string SequenceMaster_PackDate {
            get {
                return ResourceManager.GetString("SequenceMaster_PackDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PackUserName.
        /// </summary>
        public static string SequenceMaster_PackUserName {
            get {
                return ResourceManager.GetString("SequenceMaster_PackUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party From .
        /// </summary>
        public static string SequenceMaster_PartyFrom {
            get {
                return ResourceManager.GetString("SequenceMaster_PartyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party From Name.
        /// </summary>
        public static string SequenceMaster_PartyFromName {
            get {
                return ResourceManager.GetString("SequenceMaster_PartyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party To.
        /// </summary>
        public static string SequenceMaster_PartyTo {
            get {
                return ResourceManager.GetString("SequenceMaster_PartyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party To Name.
        /// </summary>
        public static string SequenceMaster_PartyToName {
            get {
                return ResourceManager.GetString("SequenceMaster_PartyToName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyToNaMe2.
        /// </summary>
        public static string SequenceMaster_PartyToNaMe2 {
            get {
                return ResourceManager.GetString("SequenceMaster_PartyToNaMe2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOption.
        /// </summary>
        public static string SequenceMaster_PrintOption {
            get {
                return ResourceManager.GetString("SequenceMaster_PrintOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Type.
        /// </summary>
        public static string SequenceMaster_QualityType {
            get {
                return ResourceManager.GetString("SequenceMaster_QualityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptTemplate.
        /// </summary>
        public static string SequenceMaster_ReceiptTemplate {
            get {
                return ResourceManager.GetString("SequenceMaster_ReceiptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence No.
        /// </summary>
        public static string SequenceMaster_SequenceNo {
            get {
                return ResourceManager.GetString("SequenceMaster_SequenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipDate.
        /// </summary>
        public static string SequenceMaster_ShipDate {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromAddress.
        /// </summary>
        public static string SequenceMaster_ShipFromAddress {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromAddress.
        /// </summary>
        public static string SequenceMaster_ShipFromAddress_SupplierSortMaster {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromAddress_SupplierSortMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromCell.
        /// </summary>
        public static string SequenceMaster_ShipFromCell {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromCell.
        /// </summary>
        public static string SequenceMaster_ShipFromCell_SupplierSortMaster {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromCell_SupplierSortMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromContact.
        /// </summary>
        public static string SequenceMaster_ShipFromContact {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromContact.
        /// </summary>
        public static string SequenceMaster_ShipFromContact_SupplierSortMaster {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromContact_SupplierSortMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromFax.
        /// </summary>
        public static string SequenceMaster_ShipFromFax {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromFax.
        /// </summary>
        public static string SequenceMaster_ShipFromFax_SupplierSortMaster {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromFax_SupplierSortMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromTel.
        /// </summary>
        public static string SequenceMaster_ShipFromTel {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipFromTel.
        /// </summary>
        public static string SequenceMaster_ShipFromTel_SupplierSortMaster {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipFromTel_SupplierSortMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceMaster {0} Shipped.
        /// </summary>
        public static string SequenceMaster_Shipped {
            get {
                return ResourceManager.GetString("SequenceMaster_Shipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToAddress.
        /// </summary>
        public static string SequenceMaster_ShipToAddress {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToCell.
        /// </summary>
        public static string SequenceMaster_ShipToCell {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipToCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToContact.
        /// </summary>
        public static string SequenceMaster_ShipToContact {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToFax.
        /// </summary>
        public static string SequenceMaster_ShipToFax {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipToFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipToTel.
        /// </summary>
        public static string SequenceMaster_ShipToTel {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipToTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipUserName.
        /// </summary>
        public static string SequenceMaster_ShipUserName {
            get {
                return ResourceManager.GetString("SequenceMaster_ShipUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string SequenceMaster_StartTime {
            get {
                return ResourceManager.GetString("SequenceMaster_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SequenceMaster_Status {
            get {
                return ResourceManager.GetString("SequenceMaster_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplierName.
        /// </summary>
        public static string SequenceMaster_SupplierName {
            get {
                return ResourceManager.GetString("SequenceMaster_SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string SequenceMaster_Title_Audit {
            get {
                return ResourceManager.GetString("SequenceMaster_Title_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseInfo.
        /// </summary>
        public static string SequenceMaster_Title_BaseInfo {
            get {
                return ResourceManager.GetString("SequenceMaster_Title_BaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string SequenceMaster_Version {
            get {
                return ResourceManager.GetString("SequenceMaster_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window Time.
        /// </summary>
        public static string SequenceMaster_WindowTime {
            get {
                return ResourceManager.GetString("SequenceMaster_WindowTime", resourceCulture);
            }
        }
    }
}
