//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SAPCustomer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SAPCustomer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.SAPCustomer", typeof(SAPCustomer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchNo.
        /// </summary>
        public static string SAPCustomer_BatchNo {
            get {
                return ResourceManager.GetString("SAPCustomer_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string SAPCustomer_BUKRS {
            get {
                return ResourceManager.GetString("SAPCustomer_BUKRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string SAPCustomer_CITY {
            get {
                return ResourceManager.GetString("SAPCustomer_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string SAPCustomer_COUNTRY {
            get {
                return ResourceManager.GetString("SAPCustomer_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string SAPCustomer_CreateDate {
            get {
                return ResourceManager.GetString("SAPCustomer_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerCode.
        /// </summary>
        public static string SAPCustomer_KUNNR {
            get {
                return ResourceManager.GetString("SAPCustomer_KUNNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isactive.
        /// </summary>
        public static string SAPCustomer_LOEVM {
            get {
                return ResourceManager.GetString("SAPCustomer_LOEVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SAPCustomer_NAME1 {
            get {
                return ResourceManager.GetString("SAPCustomer_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string SAPCustomer_PARNR {
            get {
                return ResourceManager.GetString("SAPCustomer_PARNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode.
        /// </summary>
        public static string SAPCustomer_PSTLZ {
            get {
                return ResourceManager.GetString("SAPCustomer_PSTLZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SAPCustomer_REMARK {
            get {
                return ResourceManager.GetString("SAPCustomer_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SAPCustomer_Status {
            get {
                return ResourceManager.GetString("SAPCustomer_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SAPCustomer_TELBX {
            get {
                return ResourceManager.GetString("SAPCustomer_TELBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telphone.
        /// </summary>
        public static string SAPCustomer_TELF1 {
            get {
                return ResourceManager.GetString("SAPCustomer_TELF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string SAPCustomer_TELF2 {
            get {
                return ResourceManager.GetString("SAPCustomer_TELF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string SAPCustomer_TELFX {
            get {
                return ResourceManager.GetString("SAPCustomer_TELFX", resourceCulture);
            }
        }
    }
}
