//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SAPSupplier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SAPSupplier() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.SAPSupplier", typeof(SAPSupplier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchNo.
        /// </summary>
        public static string SAPSupplier_BatchNo {
            get {
                return ResourceManager.GetString("SAPSupplier_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string SAPSupplier_BUKRS {
            get {
                return ResourceManager.GetString("SAPSupplier_BUKRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string SAPSupplier_CITY {
            get {
                return ResourceManager.GetString("SAPSupplier_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string SAPSupplier_COUNTRY {
            get {
                return ResourceManager.GetString("SAPSupplier_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateDate.
        /// </summary>
        public static string SAPSupplier_CreateDate {
            get {
                return ResourceManager.GetString("SAPSupplier_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchasGroup.
        /// </summary>
        public static string SAPSupplier_EKGRP {
            get {
                return ResourceManager.GetString("SAPSupplier_EKGRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string SAPSupplier_LIFNR {
            get {
                return ResourceManager.GetString("SAPSupplier_LIFNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string SAPSupplier_LOEVM {
            get {
                return ResourceManager.GetString("SAPSupplier_LOEVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SAPSupplier_NAME1 {
            get {
                return ResourceManager.GetString("SAPSupplier_NAME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string SAPSupplier_PARNR {
            get {
                return ResourceManager.GetString("SAPSupplier_PARNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostCode.
        /// </summary>
        public static string SAPSupplier_PSTLZ {
            get {
                return ResourceManager.GetString("SAPSupplier_PSTLZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address
        ///供应商电话
        ///MD_Address.Telphone
        ///供应商传真
        ///MD_Address.Fax
        ///供应商联系人
        ///MD_Address.Contact
        ///邮编
        ///MD_Address.PostCode
        ///电子邮箱
        ///MD_Address.Email.
        /// </summary>
        public static string SAPSupplier_REMARK {
            get {
                return ResourceManager.GetString("SAPSupplier_REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SAPSupplier_Status {
            get {
                return ResourceManager.GetString("SAPSupplier_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SAPSupplier_TELBX {
            get {
                return ResourceManager.GetString("SAPSupplier_TELBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telphone
        ///供应商传真
        ///MD_Address.Fax
        ///供应商联系人
        ///MD_Address.Contact
        ///邮编
        ///MD_Address.PostCode
        ///电子邮箱
        ///Telphone.
        /// </summary>
        public static string SAPSupplier_TELF1 {
            get {
                return ResourceManager.GetString("SAPSupplier_TELF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string SAPSupplier_TELF2 {
            get {
                return ResourceManager.GetString("SAPSupplier_TELF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string SAPSupplier_TELFX {
            get {
                return ResourceManager.GetString("SAPSupplier_TELFX", resourceCulture);
            }
        }
    }
}
