//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SAPSDNormal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SAPSDNormal() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.SAPSDNormal", typeof(SAPSDNormal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BatchNo 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_BatchNo {
            get {
                return ResourceManager.GetString("SAPSDNormal_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DISTRCHAN 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_DISTRCHAN {
            get {
                return ResourceManager.GetString("SAPSDNormal_DISTRCHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DIVISION 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_DIVISION {
            get {
                return ResourceManager.GetString("SAPSDNormal_DIVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOCDATE 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_DOCDATE {
            get {
                return ResourceManager.GetString("SAPSDNormal_DOCDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOCTYPE 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_DOCTYPE {
            get {
                return ResourceManager.GetString("SAPSDNormal_DOCTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ITMNUMBER 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_ITMNUMBER {
            get {
                return ResourceManager.GetString("SAPSDNormal_ITMNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LGORT 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_LGORT {
            get {
                return ResourceManager.GetString("SAPSDNormal_LGORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LIFEX 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_LIFEX {
            get {
                return ResourceManager.GetString("SAPSDNormal_LIFEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MATERIAL 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_MATERIAL {
            get {
                return ResourceManager.GetString("SAPSDNormal_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ORD_REASON 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_ORDREASON {
            get {
                return ResourceManager.GetString("SAPSDNormal_ORDREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PARTN_NUMB 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_PARTNNUMB {
            get {
                return ResourceManager.GetString("SAPSDNormal_PARTNNUMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRICE_DATE 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_PRICEDATE {
            get {
                return ResourceManager.GetString("SAPSDNormal_PRICEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SALES_ORG 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_SALESORG {
            get {
                return ResourceManager.GetString("SAPSDNormal_SALESORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_Status {
            get {
                return ResourceManager.GetString("SAPSDNormal_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TARGET_QTY 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_TARGETQTY {
            get {
                return ResourceManager.GetString("SAPSDNormal_TARGETQTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UniqueCode 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_UniqueCode {
            get {
                return ResourceManager.GetString("SAPSDNormal_UniqueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VRKME 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_VRKME {
            get {
                return ResourceManager.GetString("SAPSDNormal_VRKME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WADAT_IST 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_WADATIST {
            get {
                return ResourceManager.GetString("SAPSDNormal_WADATIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZCSRQSJ 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_ZCSRQSJ {
            get {
                return ResourceManager.GetString("SAPSDNormal_ZCSRQSJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZMESGUID 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_ZMESGUID {
            get {
                return ResourceManager.GetString("SAPSDNormal_ZMESGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZMESSO 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_ZMESSO {
            get {
                return ResourceManager.GetString("SAPSDNormal_ZMESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ZMESSOSEQ 的本地化字符串。
        /// </summary>
        public static string SAPSDNormal_ZMESSOSEQ {
            get {
                return ResourceManager.GetString("SAPSDNormal_ZMESSOSEQ", resourceCulture);
            }
        }
    }
}
