//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.SI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Trigger {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trigger() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SI.Trigger", typeof(Trigger).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Trigger_Description {
            get {
                return ResourceManager.GetString("Trigger_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval 的本地化字符串。
        /// </summary>
        public static string Trigger_Interval {
            get {
                return ResourceManager.GetString("Trigger_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IntervalType 的本地化字符串。
        /// </summary>
        public static string Trigger_IntervalType {
            get {
                return ResourceManager.GetString("Trigger_IntervalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Trigger_Name {
            get {
                return ResourceManager.GetString("Trigger_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NextFireTime 的本地化字符串。
        /// </summary>
        public static string Trigger_NextFireTime {
            get {
                return ResourceManager.GetString("Trigger_NextFireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PreviousFireTime 的本地化字符串。
        /// </summary>
        public static string Trigger_PreviousFireTime {
            get {
                return ResourceManager.GetString("Trigger_PreviousFireTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RepeatCount 的本地化字符串。
        /// </summary>
        public static string Trigger_RepeatCount {
            get {
                return ResourceManager.GetString("Trigger_RepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimesTriggered 的本地化字符串。
        /// </summary>
        public static string Trigger_TimesTriggered {
            get {
                return ResourceManager.GetString("Trigger_TimesTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id 的本地化字符串。
        /// </summary>
        public static string Trigger_Triggerid {
            get {
                return ResourceManager.GetString("Trigger_Triggerid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Trigger_TriggerStatusName {
            get {
                return ResourceManager.GetString("Trigger_TriggerStatusName", resourceCulture);
            }
        }
    }
}
