//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MRP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HuTo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HuTo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MRP.HuTo", typeof(HuTo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 HuTo has been added successfully. 的本地化字符串。
        /// </summary>
        public static string HuTo_Added {
            get {
                return ResourceManager.GetString("HuTo_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string HuTo_Code {
            get {
                return ResourceManager.GetString("HuTo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateDate 的本地化字符串。
        /// </summary>
        public static string HuTo_CreateDate {
            get {
                return ResourceManager.GetString("HuTo_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateUserName 的本地化字符串。
        /// </summary>
        public static string HuTo_CreateUserName {
            get {
                return ResourceManager.GetString("HuTo_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuTo has been deleted successfully. 的本地化字符串。
        /// </summary>
        public static string HuTo_Deleted {
            get {
                return ResourceManager.GetString("HuTo_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string HuTo_Description {
            get {
                return ResourceManager.GetString("HuTo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuTo _Edit 的本地化字符串。
        /// </summary>
        public static string HuTo_Edit_Title {
            get {
                return ResourceManager.GetString("HuTo_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuTo _New 的本地化字符串。
        /// </summary>
        public static string HuTo_New_Title {
            get {
                return ResourceManager.GetString("HuTo_New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HuTo has been Updated successfully. 的本地化字符串。
        /// </summary>
        public static string HuTo_Updated {
            get {
                return ResourceManager.GetString("HuTo_Updated", resourceCulture);
            }
        }
    }
}
