//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MRP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MrpExItemPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MrpExItemPlan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MRP.MrpExItemPlan", typeof(MrpExItemPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调整数.
        /// </summary>
        public static string MrpExItemPlan_AdjustQty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_AdjustQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修正数.
        /// </summary>
        public static string MrpExItemPlan_CorrectionQty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_CorrectionQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周.
        /// </summary>
        public static string MrpExItemPlan_DateIndex {
            get {
                return ResourceManager.GetString("MrpExItemPlan_DateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料号.
        /// </summary>
        public static string MrpExItemPlan_Item {
            get {
                return ResourceManager.GetString("MrpExItemPlan_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物料描述.
        /// </summary>
        public static string MrpExItemPlan_ItemDescritpion {
            get {
                return ResourceManager.GetString("MrpExItemPlan_ItemDescritpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需求平衡.
        /// </summary>
        public static string MrpExItemPlan_PlanQty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_PlanQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        public static string MrpExItemPlan_PlanVersion {
            get {
                return ResourceManager.GetString("MrpExItemPlan_PlanVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产线.
        /// </summary>
        public static string MrpExItemPlan_ProductLine {
            get {
                return ResourceManager.GetString("MrpExItemPlan_ProductLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string MrpExItemPlan_Qty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用量.
        /// </summary>
        public static string MrpExItemPlan_RateQty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_RateQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断面.
        /// </summary>
        public static string MrpExItemPlan_Section {
            get {
                return ResourceManager.GetString("MrpExItemPlan_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string MrpExItemPlan_SectionId {
            get {
                return ResourceManager.GetString("MrpExItemPlan_SectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 序号.
        /// </summary>
        public static string MrpExItemPlan_Sequence {
            get {
                return ResourceManager.GetString("MrpExItemPlan_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 班次数.
        /// </summary>
        public static string MrpExItemPlan_ShiftQty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_ShiftQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总长度.
        /// </summary>
        public static string MrpExItemPlan_TotalLength {
            get {
                return ResourceManager.GetString("MrpExItemPlan_TotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总数量.
        /// </summary>
        public static string MrpExItemPlan_TotalQty {
            get {
                return ResourceManager.GetString("MrpExItemPlan_TotalQty", resourceCulture);
            }
        }
    }
}
