//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MRP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MrpMiShiftPlan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MrpMiShiftPlan() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MRP.MrpMiShiftPlan", typeof(MrpMiShiftPlan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 调整数量 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_AdjustQty {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_AdjustQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求车数 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_CheQty {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_CheQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车数 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_CurrentCheQty {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_CurrentCheQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去向 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_HuTo {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_HuTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_Item {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料描述 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_ItemDescription {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库位 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_Location {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单数量 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_OrderedQty {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_OrderedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求来源产品 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_ParentItem {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_ParentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求来源产品 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_ParentItemDescription {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_ParentItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_PlanDate {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_PlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_PlanVersion {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_PlanVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产线 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_ProductLine {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_ProductLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求数量 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_Qty {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_Sequence {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 班次 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_Shift {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求来源路线 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_SourceFlow {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_SourceFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求来源组织 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_SourceFlowDescription {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_SourceFlowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求来源组织 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_SourceParty {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_SourceParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需求来源路线 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_SourcePartyDescription {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_SourcePartyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单包装 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_UnitCount {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_UnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string MrpMiShiftPlan_Uom {
            get {
                return ResourceManager.GetString("MrpMiShiftPlan_Uom", resourceCulture);
            }
        }
    }
}
