//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18047
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.MRP {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RccpPlanMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RccpPlanMaster() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MRP.RccpPlanMaster", typeof(RccpPlanMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消时间 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_CancelDate {
            get {
                return ResourceManager.GetString("RccpPlanMaster_CancelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消用户 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_CancelUserName {
            get {
                return ResourceManager.GetString("RccpPlanMaster_CancelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭时间 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_CloseDate {
            get {
                return ResourceManager.GetString("RccpPlanMaster_CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭用户 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_CloseUserName {
            get {
                return ResourceManager.GetString("RccpPlanMaster_CloseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_CreateDate {
            get {
                return ResourceManager.GetString("RccpPlanMaster_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_CreateUserName {
            get {
                return ResourceManager.GetString("RccpPlanMaster_CreateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间索引 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_DateIndex {
            get {
                return ResourceManager.GetString("RccpPlanMaster_DateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间类型 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_DateType {
            get {
                return ResourceManager.GetString("RccpPlanMaster_DateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_Edit_Title {
            get {
                return ResourceManager.GetString("RccpPlanMaster_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 释放 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_IsRelease {
            get {
                return ResourceManager.GetString("RccpPlanMaster_IsRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_PlanVersion {
            get {
                return ResourceManager.GetString("RccpPlanMaster_PlanVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 车型计划版本 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_RccpPlanVersion {
            get {
                return ResourceManager.GetString("RccpPlanMaster_RccpPlanVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 释放时间 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_ReleaseDate {
            get {
                return ResourceManager.GetString("RccpPlanMaster_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 释放用户 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_ReleaseUserName {
            get {
                return ResourceManager.GetString("RccpPlanMaster_ReleaseUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快照版本 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_SnapTime {
            get {
                return ResourceManager.GetString("RccpPlanMaster_SnapTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string RccpPlanMaster_Status {
            get {
                return ResourceManager.GetString("RccpPlanMaster_Status", resourceCulture);
            }
        }
    }
}
