delete from CUST_DeferredFeedCounter
delete from CUST_OpReport
delete from INV_LocTransDet
delete from INV_LocTransDet_0
delete from INV_LocTransDet_1
delete from INV_LocTransDet_2
delete from INV_LocTransDet_3
delete from INV_LocTransDet_4
delete from INV_LocTransDet_5
delete from INV_LocTransDet_6
delete from INV_LocTransDet_7
delete from INV_LocTransDet_8
delete from INV_LocTransDet_9
delete from INV_LocTransDet_10
delete from INV_LocTransDet_11
delete from INV_LocTransDet_12
delete from INV_LocTransDet_13
delete from INV_LocTransDet_14
delete from INV_LocTransDet_15
delete from INV_LocTransDet_16
delete from INV_LocTransDet_17
delete from INV_LocTransDet_18
delete from INV_LocTransDet_19
delete from INV_LocTrans
delete from INV_LocTrans_0
delete from INV_LocTrans_1
delete from INV_LocTrans_2
delete from INV_LocTrans_3
delete from INV_LocTrans_4
delete from INV_LocTrans_5
delete from INV_LocTrans_6
delete from INV_LocTrans_7
delete from INV_LocTrans_8
delete from INV_LocTrans_9
delete from INV_LocTrans_10
delete from INV_LocTrans_11
delete from INV_LocTrans_12
delete from INV_LocTrans_13
delete from INV_LocTrans_14
delete from INV_LocTrans_15
delete from INV_LocTrans_16
delete from INV_LocTrans_17
delete from INV_LocTrans_18
delete from INV_LocTrans_19
delete from INV_LocationLotDet
delete from INV_LocationLotDet_0
delete from INV_LocationLotDet_1
delete from INV_LocationLotDet_2
delete from INV_LocationLotDet_3
delete from INV_LocationLotDet_4
delete from INV_LocationLotDet_5
delete from INV_LocationLotDet_6
delete from INV_LocationLotDet_7
delete from INV_LocationLotDet_8
delete from INV_LocationLotDet_9
delete from INV_LocationLotDet_10
delete from INV_LocationLotDet_11
delete from INV_LocationLotDet_12
delete from INV_LocationLotDet_13
delete from INV_LocationLotDet_14
delete from INV_LocationLotDet_15
delete from INV_LocationLotDet_16
delete from INV_LocationLotDet_17
delete from INV_LocationLotDet_18
delete from INV_LocationLotDet_19
delete from INV_StockTakeResult
delete from INV_StockTakeDet
delete from INV_StockTakeInv
delete from INV_StockTakeItem
delete from INV_StockTakeLoc
delete from INV_StockTakeMstr
delete from INP_ConcessionDet
delete from INP_ConcessionMstr
delete from INP_RejectDet
delete from INP_RejectMstr
delete from INP_InspectResult
delete from INP_InspectDet
delete from INP_InspectMstr
delete from ORD_OrderBackflushDet
delete from ORD_OrderBindingDet
delete from ORD_OrderBinding
delete from ORD_OrderBomDet
delete from ORD_OrderOp
delete from ORD_RecLocationDet
delete from ORD_RecLocationDet_0
delete from ORD_RecLocationDet_1
delete from ORD_RecLocationDet_2
delete from ORD_RecLocationDet_3
delete from ORD_RecLocationDet_4
delete from ORD_RecLocationDet_5
delete from ORD_RecLocationDet_6
delete from ORD_RecLocationDet_7
delete from ORD_RecLocationDet_8
delete from PRD_PlanBackflush
delete from ORD_RecDet
delete from ORD_RecDet_0
delete from ORD_RecDet_1
delete from ORD_RecDet_2
delete from ORD_RecDet_3
delete from ORD_RecDet_4
delete from ORD_RecDet_5
delete from ORD_RecDet_6
delete from ORD_RecDet_7
delete from ORD_RecDet_8
delete from ORD_RecMstr
delete from ORD_RecMstr_0
delete from ORD_RecMstr_1
delete from ORD_RecMstr_2
delete from ORD_RecMstr_3
delete from ORD_RecMstr_4
delete from ORD_RecMstr_5
delete from ORD_RecMstr_6
delete from ORD_RecMstr_7
delete from ORD_RecMstr_8
delete from BIL_BillTrans
delete from BIL_ActBill
delete from BIL_PlanBill
delete from BIL_BillDet
delete from BIL_BillMstr
delete from BIL_PlanBillTrans
delete from ORD_IpLocationDet
delete from ORD_IpLocationDet_0
delete from ORD_IpLocationDet_1
delete from ORD_IpLocationDet_2
delete from ORD_IpLocationDet_3
delete from ORD_IpLocationDet_4
delete from ORD_IpLocationDet_5
delete from ORD_IpLocationDet_6
delete from ORD_IpLocationDet_7
delete from ORD_IpLocationDet_8
delete from ORD_IpDet
delete from ORD_IpDet_0
delete from ORD_IpDet_1
delete from ORD_IpDet_2
delete from ORD_IpDet_3
delete from ORD_IpDet_4
delete from ORD_IpDet_5
delete from ORD_IpDet_6
delete from ORD_IpDet_7
delete from ORD_IpDet_8
delete from ORD_IpMstr
delete from ORD_IpMstr_0
delete from ORD_IpMstr_1
delete from ORD_IpMstr_2
delete from ORD_IpMstr_3
delete from ORD_IpMstr_4
delete from ORD_IpMstr_5
delete from ORD_IpMstr_6
delete from ORD_IpMstr_7
delete from ORD_IpMstr_8
delete from ORD_PickListResult
delete from ORD_PickListDet
delete from ORD_PickListMstr
delete from ORD_SeqDet
delete from ORD_SeqMstr
delete from ORD_OrderDet
delete from ORD_OrderDet_0
delete from ORD_OrderDet_1
delete from ORD_OrderDet_2
delete from ORD_OrderDet_3
delete from ORD_OrderDet_4
delete from ORD_OrderDet_5
delete from ORD_OrderDet_6
delete from ORD_OrderDet_7
delete from ORD_OrderDet_8
delete from ORD_OrderMstr
delete from ORD_OrderMstr_0
delete from ORD_OrderMstr_1
delete from ORD_OrderMstr_2
delete from ORD_OrderMstr_3
delete from ORD_OrderMstr_4
delete from ORD_OrderMstr_5
delete from ORD_OrderMstr_6
delete from ORD_OrderMstr_7
delete from ORD_OrderMstr_8
delete from CUST_OpReport
delete from ORD_MiscOrderLocationDet
delete from ORD_MiscOrderDet
delete from ORD_MiscOrderMstr
delete from PRD_ProdLineLocationDet
delete from INV_Hu
delete from SYS_NumCtrl


--MRP
truncate table [MRP_ActiveOrder]
truncate table [MRP_FlowDetail]
truncate table [MRP_InventoryBalance]
truncate table [MRP_MrpExDateIndex]
truncate table [MRP_MrpExItemPlan]
truncate table [MRP_MrpExOrder]
truncate table [MRP_MrpExPlan]
truncate table [MRP_MrpExPlanMaster]
truncate table [MRP_MrpExScrap]
truncate table [MRP_MrpExSectionPlan]
truncate table [MRP_MrpExShiftPlan]
truncate table [MRP_MrpExWorkHour]
truncate table [MRP_MrpFiPlan]
truncate table [MRP_MrpFiShiftPlan]
truncate table [MRP_MrpLog]
truncate table [MRP_MrpMiDateIndex]
truncate table [MRP_MrpMiPlan]
truncate table [MRP_MrpMiPlanDetail]
truncate table [MRP_MrpMiShiftPlan]
truncate table [MRP_MrpPlan]
truncate table [MRP_MrpPlanLog]
truncate table [MRP_MrpPlanMaster]
truncate table [MRP_MrpShipPlan]
truncate table [MRP_MrpShipPlanGroup]
truncate table [MRP_ProdLineEx]
truncate table [MRP_ProdLineExInstance]
truncate table [MRP_PurchasePlan]
truncate table [MRP_PurchasePlanMaster]
truncate table [MRP_RccpFiPlan]
truncate table [MRP_RccpLog]
truncate table [MRP_RccpMiPlan]
truncate table [MRP_RccpPlan]
truncate table [MRP_RccpPlanLog]
truncate table [MRP_RccpPlanMaster]
truncate table [MRP_RccpTransGroup]
truncate table [MRP_SnapLog]
truncate table [MRP_SnapMachine]
truncate table [MRP_SnapMaster]
truncate table [MRP_SnapMrpPlan]
truncate table [MRP_SnapProdLineEx]
truncate table [MRP_TransferPlan]
truncate table [MRP_TransferPlanMaster]
truncate table [MRP_TransitOrder]
--truncate table [MRP_WeekIndex]
truncate table [MRP_WorkCalendar]



--truncate
truncate table [CUST_DeferredFeedCounter]
truncate table [CUST_OpReport]
truncate table [INV_LocTransDet]
truncate table [INV_LocTransDet_0]
truncate table [INV_LocTransDet_1]
truncate table [INV_LocTransDet_2]
truncate table [INV_LocTransDet_3]
truncate table [INV_LocTransDet_4]
truncate table [INV_LocTransDet_5]
truncate table [INV_LocTransDet_6]
truncate table [INV_LocTransDet_7]
truncate table [INV_LocTransDet_8]
truncate table [INV_LocTransDet_9]
truncate table [INV_LocTransDet_10]
truncate table [INV_LocTransDet_11]
truncate table [INV_LocTransDet_12]
truncate table [INV_LocTransDet_13]
truncate table [INV_LocTransDet_14]
truncate table [INV_LocTransDet_15]
truncate table [INV_LocTransDet_16]
truncate table [INV_LocTransDet_17]
truncate table [INV_LocTransDet_18]
truncate table [INV_LocTransDet_19]
truncate table [INV_LocTrans]
truncate table [INV_LocTrans_0]
truncate table [INV_LocTrans_1]
truncate table [INV_LocTrans_2]
truncate table [INV_LocTrans_3]
truncate table [INV_LocTrans_4]
truncate table [INV_LocTrans_5]
truncate table [INV_LocTrans_6]
truncate table [INV_LocTrans_7]
truncate table [INV_LocTrans_8]
truncate table [INV_LocTrans_9]
truncate table [INV_LocTrans_10]
truncate table [INV_LocTrans_11]
truncate table [INV_LocTrans_12]
truncate table [INV_LocTrans_13]
truncate table [INV_LocTrans_14]
truncate table [INV_LocTrans_15]
truncate table [INV_LocTrans_16]
truncate table [INV_LocTrans_17]
truncate table [INV_LocTrans_18]
truncate table [INV_LocTrans_19]
truncate table [INV_LocationLotDet]
truncate table [INV_LocationLotDet_0]
truncate table [INV_LocationLotDet_1]
truncate table [INV_LocationLotDet_2]
truncate table [INV_LocationLotDet_3]
truncate table [INV_LocationLotDet_4]
truncate table [INV_LocationLotDet_5]
truncate table [INV_LocationLotDet_6]
truncate table [INV_LocationLotDet_7]
truncate table [INV_LocationLotDet_8]
truncate table [INV_LocationLotDet_9]
truncate table [INV_LocationLotDet_10]
truncate table [INV_LocationLotDet_11]
truncate table [INV_LocationLotDet_12]
truncate table [INV_LocationLotDet_13]
truncate table [INV_LocationLotDet_14]
truncate table [INV_LocationLotDet_15]
truncate table [INV_LocationLotDet_16]
truncate table [INV_LocationLotDet_17]
truncate table [INV_LocationLotDet_18]
truncate table [INV_LocationLotDet_19]
truncate table [INV_StockTakeResult]
truncate table [INV_StockTakeDet]
truncate table [INV_StockTakeItem]
truncate table [INV_StockTakeLoc]
--truncate table [INV_StockTakeMstr]
truncate table [INP_ConcessionDet]
--truncate table [INP_ConcessionMstr]
truncate table [INP_RejectDet]
--truncate table [INP_RejectMstr]
--truncate table [INP_InspectResult]
truncate table [INP_InspectDet]
--truncate table [INP_InspectMstr]
truncate table [ORD_OrderBackflushDet]
truncate table [ORD_OrderBindingDet]
--truncate table [ORD_OrderBinding]
--truncate table [ORD_OrderBomDet]
truncate table [ORD_OrderOp]
truncate table [ORD_RecLocationDet]
truncate table [ORD_RecLocationDet_0]
truncate table [ORD_RecLocationDet_1]
truncate table [ORD_RecLocationDet_2]
truncate table [ORD_RecLocationDet_3]
truncate table [ORD_RecLocationDet_4]
truncate table [ORD_RecLocationDet_5]
truncate table [ORD_RecLocationDet_6]
truncate table [ORD_RecLocationDet_7]
truncate table [ORD_RecLocationDet_8]
truncate table [PRD_PlanBackflush]
truncate table [ORD_RecDet]
truncate table [ORD_RecDet_0]
truncate table [ORD_RecDet_1]
truncate table [ORD_RecDet_2]
truncate table [ORD_RecDet_3]
truncate table [ORD_RecDet_4]
truncate table [ORD_RecDet_5]
truncate table [ORD_RecDet_6]
truncate table [ORD_RecDet_7]
truncate table [ORD_RecDet_8]
truncate table [ORD_RecMstr]
truncate table [ORD_RecMstr_0]
truncate table [ORD_RecMstr_1]
truncate table [ORD_RecMstr_2]
truncate table [ORD_RecMstr_3]
truncate table [ORD_RecMstr_4]
truncate table [ORD_RecMstr_5]
truncate table [ORD_RecMstr_6]
truncate table [ORD_RecMstr_7]
truncate table [ORD_RecMstr_8]
truncate table [BIL_BillTrans]
truncate table [BIL_BillDet]
--truncate table [BIL_ActBill]
--truncate table [BIL_PlanBill]
--truncate table [BIL_PlanBillTrans]
truncate table [ORD_IpLocationDet]
truncate table [ORD_IpLocationDet_0]
truncate table [ORD_IpLocationDet_1]
truncate table [ORD_IpLocationDet_2]
truncate table [ORD_IpLocationDet_3]
truncate table [ORD_IpLocationDet_4]
truncate table [ORD_IpLocationDet_5]
truncate table [ORD_IpLocationDet_6]
truncate table [ORD_IpLocationDet_7]
truncate table [ORD_IpLocationDet_8]
truncate table [ORD_IpDet]
truncate table [ORD_IpDet_0]
truncate table [ORD_IpDet_1]
truncate table [ORD_IpDet_2]
truncate table [ORD_IpDet_3]
truncate table [ORD_IpDet_4]
truncate table [ORD_IpDet_5]
truncate table [ORD_IpDet_6]
truncate table [ORD_IpDet_7]
truncate table [ORD_IpDet_8]
truncate table [ORD_IpMstr]
truncate table [ORD_IpMstr_0]
truncate table [ORD_IpMstr_1]
truncate table [ORD_IpMstr_2]
truncate table [ORD_IpMstr_3]
truncate table [ORD_IpMstr_4]
truncate table [ORD_IpMstr_5]
truncate table [ORD_IpMstr_6]
truncate table [ORD_IpMstr_7]
truncate table [ORD_IpMstr_8]
truncate table [ORD_PickListResult]
--truncate table [ORD_PickListDet]
--truncate table [ORD_PickListMstr]
truncate table [ORD_SeqDet]
--truncate table [ORD_SeqMstr]
truncate table [ORD_OrderDet]
truncate table [ORD_OrderDet_0]
truncate table [ORD_OrderDet_1]
truncate table [ORD_OrderDet_2]
truncate table [ORD_OrderDet_3]
truncate table [ORD_OrderDet_4]
truncate table [ORD_OrderDet_5]
truncate table [ORD_OrderDet_6]
truncate table [ORD_OrderDet_7]
truncate table [ORD_OrderDet_8]
truncate table [ORD_OrderMstr]
truncate table [ORD_OrderMstr_0]
truncate table [ORD_OrderMstr_1]
truncate table [ORD_OrderMstr_2]
truncate table [ORD_OrderMstr_3]
truncate table [ORD_OrderMstr_4]
truncate table [ORD_OrderMstr_5]
truncate table [ORD_OrderMstr_6]
truncate table [ORD_OrderMstr_7]
truncate table [ORD_OrderMstr_8]
truncate table [CUST_OpReport]
truncate table [ORD_MiscOrderLocationDet]
--truncate table [ORD_MiscOrderDet]
--truncate table [ORD_MiscOrderMstr]
truncate table [PRD_ProdLineLocationDet]
--truncate table [INV_Hu]
truncate table [SYS_NumCtrl]

truncate table ORD_ShipmentDet
truncate table ORD_ShipmentMstr
truncate table BAT_RunLog
truncate table ORD_OrderTracer
truncate table CUST_PubPrintOrder

truncate table INV_StockTakeInv
delete from INV_PickTrans
truncate table INV_PickTrans
delete from INV_FreezeTrans
truncate table INV_FreezeTrans
delete from INV_ItemExchange
truncate table INV_ItemExchange


